const FEEDS=[
 {source:"TRT Haber",publisher:"TRT Haber",url:"https://www.trthaber.com/sondakika_articles.rss"},
 {source:"TRT Gündem",publisher:"TRT Haber",url:"https://www.trthaber.com/gundem_articles.rss"},
 {source:"Habertürk",publisher:"Habertürk",url:"https://www.haberturk.com/rss"},
 {source:"Habertürk Gündem",publisher:"Habertürk",url:"https://www.haberturk.com/rss/kategori/gundem.xml"},
 {source:"Habertürk Ekonomi",publisher:"Habertürk",url:"https://www.haberturk.com/rss/ekonomi.xml"},
 {source:"Haberler.com",publisher:"Haberler.com",url:"https://rss.haberler.com/RssNew.aspx"}
];
const X_POST_URL="https://api.x.com/2/tweets";
const STOP=new Set("ve veya ile için bir bu şu o da de mi mı mu mü son dakika haber haberi haberleri yeni göre olarak daha en çok ise var oldu olan ilgili ardından sonra önce bugün türkiye türkiyede".split(" "));
function decodeXml(s=""){return s.replace(/<!\[CDATA\[|\]\]>/g,"").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");}
function items(xml,f){return [...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,15).map(m=>{const x=m[1];const get=t=>decodeXml((x.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`,"i"))||[])[1]||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();return{title:get("title"),link:get("link")||get("guid"),pubDate:get("pubDate")||get("dc:date")||get("date"),source:get("source")||f.source,publisher:f.publisher};});}
async function ensureSchema(env){await env.DB.batch([env.DB.prepare("CREATE TABLE IF NOT EXISTS published_news (id INTEGER PRIMARY KEY AUTOINCREMENT,fingerprint TEXT NOT NULL UNIQUE,title TEXT NOT NULL,source_url TEXT,x_post_id TEXT,published_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_published_news_time ON published_news(published_at)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS worker_state (key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS news_queue (fingerprint TEXT PRIMARY KEY,title TEXT NOT NULL,source_url TEXT,primary_source TEXT NOT NULL,sources TEXT NOT NULL,source_count INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'ready',first_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_news_queue_status ON news_queue(status,last_seen)")]);}
function normalizeTitle(text){return text.toLocaleLowerCase("tr-TR").replace(/[^a-z0-9çğıöşü ]/gi," ").replace(/\s+/g," ").trim();}
function tokens(text){return new Set(normalizeTitle(text).split(" ").filter(x=>x.length>2&&!STOP.has(x)));}
function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let inter=0;for(const x of A)if(B.has(x))inter++;return inter/Math.min(A.size,B.size);}
async function fingerprint(text){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(normalizeTitle(text)));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function pct(s){return encodeURIComponent(String(s)).replace(/[!'()*]/g,c=>`%${c.charCodeAt(0).toString(16).toUpperCase()}`);}
function b64(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s);}
async function hmacSha1(key,data){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(key),{name:"HMAC",hash:"SHA-1"},false,["sign"]);return b64(new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(data))));}
async function oauthHeader(env,method,url){for(const k of ["X_API_KEY","X_API_SECRET","X_ACCESS_TOKEN","X_ACCESS_TOKEN_SECRET"])if(!env[k])throw new Error(`missing_${k}`);const p={oauth_consumer_key:env.X_API_KEY,oauth_nonce:crypto.randomUUID().replaceAll("-",""),oauth_signature_method:"HMAC-SHA1",oauth_timestamp:String(Math.floor(Date.now()/1000)),oauth_token:env.X_ACCESS_TOKEN,oauth_version:"1.0"};const param=Object.entries(p).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${pct(k)}=${pct(v)}`).join("&");const base=[method.toUpperCase(),pct(url),pct(param)].join("&");p.oauth_signature=await hmacSha1(`${pct(env.X_API_SECRET)}&${pct(env.X_ACCESS_TOKEN_SECRET)}`,base);return "OAuth "+Object.entries(p).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${pct(k)}=\"${pct(v)}\"`).join(", ");}
function postText(n){let title=n.title.replace(/\s+-\s+[^-]{2,60}$/,"").trim();const source=n.source?`\n\nKaynak: ${n.source}`:"";const suffix="\n\n#SonDakika #Gündem";const room=280-source.length-suffix.length;if(title.length>room)title=title.slice(0,Math.max(0,room-1)).trimEnd()+"…";return title+source+suffix;}
async function countToday(env){const r=await env.DB.prepare("SELECT COUNT(*) n FROM published_news WHERE published_at >= datetime('now','start of day')").first();return Number(r?.n||0);}
async function publishX(env,n){const auth=await oauthHeader(env,"POST",X_POST_URL);const r=await fetch(X_POST_URL,{method:"POST",headers:{Authorization:auth,"Content-Type":"application/json"},body:JSON.stringify({text:postText(n)})});const raw=await r.text();let body={};try{body=JSON.parse(raw);}catch{}if(!r.ok||!body?.data?.id)throw new Error(`x_http_${r.status}:${raw.slice(0,400)}`);return body.data.id;}
async function saveState(env,state){await env.DB.prepare("INSERT INTO worker_state(key,value,updated_at) VALUES('last_scan',?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(JSON.stringify(state)).run();}
async function fetchFeeds(){return Promise.all(FEEDS.map(async f=>{try{const r=await fetch(f.url,{headers:{"User-Agent":"90Gundem/1.0","Accept":"application/rss+xml, application/xml, text/xml;q=0.9, */*;q=0.5"}});if(!r.ok)return{...f,ok:false,status:r.status,items:[]};return{...f,ok:true,status:r.status,items:items(await r.text(),f)};}catch(e){return{...f,ok:false,status:0,error:String(e?.message||e),items:[]};}}));}
function verifiedClusters(fresh,threshold=.52){const clusters=[];for(const n of fresh){let best=null,bestScore=0;for(const c of clusters){const score=similarity(n.title,c.primary.title);if(score>bestScore){bestScore=score;best=c;}}if(best&&bestScore>=threshold){best.items.push(n);best.publishers.add(n.publisher);if(new Date(n.pubDate)>new Date(best.primary.pubDate))best.primary=n;}else clusters.push({primary:n,items:[n],publishers:new Set([n.publisher])});}return clusters.filter(c=>c.publishers.size>=2).sort((a,b)=>new Date(b.primary.pubDate)-new Date(a.primary.pubDate));}
async function queueCluster(env,c){const fp=await fingerprint(c.primary.title);const sources=[...c.publishers];await env.DB.prepare("INSERT INTO news_queue(fingerprint,title,source_url,primary_source,sources,source_count,status,last_seen) VALUES(?,?,?,?,?,?, 'ready',CURRENT_TIMESTAMP) ON CONFLICT(fingerprint) DO UPDATE SET sources=excluded.sources,source_count=excluded.source_count,last_seen=CURRENT_TIMESTAMP").bind(fp,c.primary.title,c.primary.link,c.primary.source,JSON.stringify(sources),sources.length).run();return{...c.primary,fp,sources};}
async function scan(env,maxAgeOverride=null,mode="scheduled"){await ensureSchema(env);const maxAge=(maxAgeOverride??Number(env.X_MAX_AGE_MINUTES||3))*60000,now=Date.now();const feeds=await fetchFeeds();const all=feeds.flatMap(f=>f.items);const fresh=all.filter(x=>{const ts=new Date(x.pubDate).getTime(),age=now-ts;return x.title&&Number.isFinite(ts)&&age>=0&&age<=maxAge;}).sort((a,b)=>new Date(b.pubDate)-new Date(a.pubDate));const verified=verifiedClusters(fresh,Number(env.NEWS_TITLE_SIMILARITY||.52));const queued=[];for(const c of verified.slice(0,5))queued.push(await queueCluster(env,c));const enabled=String(env.X_PUBLISH_ENABLED).toLowerCase()==="true",limit=Math.max(0,Number(env.X_DAILY_POST_LIMIT||1));let used=await countToday(env),published=0,lastError=null,lastCandidate=null;for(const n of queued){if(await env.DB.prepare("SELECT 1 FROM published_news WHERE fingerprint=? LIMIT 1").bind(n.fp).first())continue;lastCandidate={title:n.title,source:n.source,sources:n.sources,pubDate:n.pubDate};if(!enabled||used>=limit)continue;try{const id=await publishX(env,n);await env.DB.prepare("INSERT INTO published_news(fingerprint,title,source_url,x_post_id) VALUES(?,?,?,?)").bind(n.fp,n.title,n.link,id).run();await env.DB.prepare("UPDATE news_queue SET status='published',last_seen=CURRENT_TIMESTAMP WHERE fingerprint=?").bind(n.fp).run();used++;published++;lastCandidate={...lastCandidate,x_post_id:id};break;}catch(e){lastError=String(e?.message||e);break;}}const state={at:new Date().toISOString(),mode,max_age_minutes:maxAge/60000,feed_status:feeds.map(f=>({source:f.source,ok:f.ok,status:f.status,items:f.items.length})),fetched:all.length,fresh:fresh.length,verified:verified.length,queued:queued.length,published,used,limit,publishing:enabled,lastCandidate,lastError};await saveState(env,state);return state;}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==="/health")return Response.json({status:"ok",service:"90gundem-cloudflare",publishing:String(env.X_PUBLISH_ENABLED).toLowerCase()==="true",credentials_ready:["X_API_KEY","X_API_SECRET","X_ACCESS_TOKEN","X_ACCESS_TOKEN_SECRET"].every(k=>Boolean(env[k])),feeds:FEEDS.length,verification:"2-distinct-publishers"});if(u.pathname==="/status"){try{await ensureSchema(env);const s=await env.DB.prepare("SELECT value,updated_at FROM worker_state WHERE key='last_scan'").first();const q=await env.DB.prepare("SELECT COUNT(*) n FROM news_queue WHERE status='ready'").first();return Response.json({status:"ok",queue_ready:Number(q?.n||0),last_scan:s?{...JSON.parse(s.value),updated_at:s.updated_at}:null});}catch(e){return Response.json({status:"error",error:String(e?.message||e)},{status:500});}}if(u.pathname==="/run-once"){try{const result=await scan(env,60,"manual-verification-test");return Response.json({status:"ok",...result});}catch(e){return Response.json({status:"error",error:String(e?.message||e)},{status:500});}}return new Response("90+ GUNDEM Cloudflare Worker",{status:200});},async scheduled(controller,env,ctx){ctx.waitUntil(scan(env,null,"scheduled").catch(e=>saveState(env,{at:new Date().toISOString(),fatalError:String(e?.message||e)}).catch(()=>{})));}};
