import live from './index-v13.js';
import { backfill2h } from './backfill-2h.js';
import { fetchPusholder } from './pusholder.js';
import { enrichNews } from './openrouter.js';

const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü ]/gi,' ').replace(/\s+/g,' ').trim();
const words=s=>new Set(norm(s).split(' ').filter(x=>x.length>3));
function similar(a,b){const A=words(a),B=words(b);let n=0;for(const x of A)if(B.has(x))n++;return A.size&&B.size&&n>=3&&n/Math.min(A.size,B.size)>=.38}
async function hash(s){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(norm(s)));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,48)}
function category(i){const n=norm(i.title+' '+i.description);if(/enflasyon|faiz|dolar|euro|altın fiyat|gram altın|borsa|ekonomi/.test(n))return'EKONOMİ';if(/futbol|voleybol|basketbol|şampiyon|final|transfer/.test(n))return'SPOR';if(/savaş|ateşkes|iran|israil|gazze|rusya|ukrayna|abd|suriye/.test(n))return'DÜNYA';if(/cumhurbaşkan|bakan|tbmm|meclis|parti|seçim/.test(n))return'SİYASET';return'GÜNDEM'}
function tags(i){return(i.ai_hashtags?.length?i.ai_hashtags:['#SonDakika','#Gündem']).filter(x=>/^#[\p{L}\p{N}_]{2,30}$/u.test(String(x))).slice(0,3)}
function short(s,n=82){s=clean(s);if(s.length<=n)return s;const c=s.slice(0,n+1),p=c.lastIndexOf(' ');return c.slice(0,p>35?p:n).replace(/[,:;\-]+$/,'')}
function xtext(i){const hs=tags(i).join(' '),h=`🔴 SON DAKİKA | ${short(i.title)}`,d=clean(i.description);let room=280-h.length-hs.length-6,b=d;if(b.length>room){const c=b.slice(0,Math.max(0,room)),p=c.lastIndexOf(' ');b=c.slice(0,p>40?p:room).replace(/[,:;\-]+$/,'')+'.'}return `${h}\n\n${b}\n\n${hs}`.slice(0,280)}
function html(i){const photo=i.image?`<img class="p" src="${esc(i.image)}">`:'';return`<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;width:1080px;height:1080px;background:#080a0f;color:#fff;font-family:Arial,sans-serif}.c{position:relative;width:1080px;height:1080px;overflow:hidden}.p{position:absolute;width:100%;height:690px;object-fit:cover}.s{position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.12) 42%,#080a0f 67%)}.b{position:absolute;top:40px;left:45px;background:#090b10dd;border-radius:40px;padding:18px 25px;font-size:30px;font-weight:900}.b em{color:#ef233c;font-style:normal}.q{position:absolute;left:50px;right:50px;bottom:55px}.k{display:inline-block;background:#ed1b2e;padding:11px 18px;font-size:18px;font-weight:900}.t{font-size:49px;line-height:1.05;font-weight:1000;text-transform:uppercase;margin:20px 0 17px;max-height:160px;overflow:hidden}.l{width:150px;height:7px;background:#ed1b2e;margin-bottom:18px}.d{font-size:25px;line-height:1.35;max-height:108px;overflow:hidden;color:#eee}.f{margin-top:28px;padding-top:16px;border-top:1px solid #333;display:flex;justify-content:space-between;font-weight:800}.h{color:#ffd43b}</style></head><body><div class="c">${photo}<div class="s"></div><div class="b">90<em>+</em> GÜNDEM</div><div class="q"><div class="k">SON DAKİKA • ${category(i)}</div><div class="t">${esc(i.title)}</div><div class="l"></div><div class="d">${esc(i.description)}</div><div class="f"><span>✓ 90+ GÜNDEM</span><span class="h">@90plusgndm</span></div></div></div></body></html>`}
async function send(env,i){const row=await env.DB.prepare("SELECT value FROM worker_state WHERE key='telegram_chat_id'").first(),chat=env.TELEGRAM_CHAT_ID||row?.value;if(!chat||!env.TELEGRAM_BOT_TOKEN||!env.BROWSER)return false;const r=await env.BROWSER.quickAction('screenshot',{html:html(i),viewport:{width:1080,height:1080},screenshotOptions:{type:'png',fullPage:false}});if(!r.ok)throw new Error('browser_'+r.status);const x=xtext(i),f=new FormData();f.append('chat_id',String(chat));f.append('photo',new Blob([new Uint8Array(await r.arrayBuffer())],{type:'image/png'}),`90gundem-pusholder-${i.pusholder_id}.png`);f.append('caption',`🔴 90+ GÜNDEM\n\n${i.title}\n\n${i.description}\n\n${tags(i).join(' ')}`);f.append('reply_markup',JSON.stringify({inline_keyboard:[[{text:`𝕏 X’TE PAYLAŞ • ${x.length}/280`,url:`https://twitter.com/intent/tweet?text=${encodeURIComponent(x)}`}]]}));const t=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendPhoto`,{method:'POST',body:f}),j=await t.json();if(!j.ok)throw new Error('telegram:'+j.description);return true}
async function pusholderRun(env,manual=false){await env.DB.prepare('CREATE TABLE IF NOT EXISTS worker_state(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)').run();await env.DB.prepare('CREATE TABLE IF NOT EXISTS speed_queue(fingerprint TEXT PRIMARY KEY,title TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)').run();const items=await fetchPusholder(),now=Date.now(),fresh=items.filter(i=>now-i.ts>=0&&now-i.ts<=10*60000).sort((a,b)=>a.ts-b.ts);let notified=0,skipped=0,failed=0;for(const p of fresh){const key=`pusholder:${p.pusholder_id}`,seen=await env.DB.prepare('SELECT value FROM worker_state WHERE key=?').bind(key).first();if(seen){skipped++;continue}const duplicateRows=await env.DB.prepare("SELECT title FROM speed_queue WHERE created_at >= datetime('now','-30 minutes') ORDER BY created_at DESC LIMIT 40").all();if((duplicateRows.results||[]).some(x=>similar(x.title,p.title))){await env.DB.prepare('INSERT INTO worker_state(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind(key,'duplicate').run();skipped++;continue}try{let i=p;if(env.OPENROUTER_API_KEY)i={...p,...await enrichNews(env,{primary:p,items:[p]}),image:p.image,link:p.link,pusholder_id:p.pusholder_id};const fp=await hash(i.title);i={...i,fp};if(await send(env,i)){notified++;await env.DB.prepare("INSERT OR IGNORE INTO speed_queue(fingerprint,title,status) VALUES(?,?,'share_ready')").bind(fp,i.title).run();await env.DB.prepare('INSERT INTO worker_state(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind(key,'sent').run()}}catch(e){failed++;await env.DB.prepare('INSERT INTO worker_state(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind(key,'error:'+String(e?.message||e).slice(0,120)).run()}}const out={status:'ok',version:'pusholder-fastlane-v1',manual,scanned:items.length,fresh:fresh.length,telegram_notified:notified,dedupe_skipped:skipped,failed};await env.DB.prepare('INSERT INTO worker_state(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind('pusholder_status',JSON.stringify(out)).run();return out}

export default {
  async fetch(req, env, ctx) {
    const u=new URL(req.url);
    if(u.pathname==='/backfill-2h'){try{return Response.json(await backfill2h(env))}catch(e){return Response.json({status:'error',version:'backfill-2h-v1',error:String(e?.message||e)},{status:500})}}
    if(u.pathname==='/pusholder-test'){try{return Response.json(await pusholderRun(env,true))}catch(e){return Response.json({status:'error',version:'pusholder-fastlane-v1',error:String(e?.message||e)},{status:500})}}
    if(u.pathname==='/pusholder-status'){const r=await env.DB.prepare("SELECT value,updated_at FROM worker_state WHERE key='pusholder_status'").first();return Response.json(r?{...JSON.parse(r.value),updated_at:r.updated_at}:{status:'waiting',version:'pusholder-fastlane-v1'})}
    if(u.pathname==='/health'){const r=await live.fetch(req,env,ctx);let d={};try{d=await r.clone().json()}catch{}return Response.json({...d,version:'speed-publish-v21',backfill_2h:true,pusholder_fastlane:true,pusholder_poll_minutes:2})}
    return live.fetch(req,env,ctx);
  },
  async scheduled(event,env,ctx){ctx.waitUntil(pusholderRun(env,false));return live.scheduled(event,env,ctx)}
};