import { enrichNews } from "./openrouter.js";

const FEEDS=[
["TRT Haber","TRT Haber","https://www.trthaber.com/sondakika_articles.rss"],["TRT Gündem","TRT Haber","https://www.trthaber.com/gundem_articles.rss"],["Habertürk","Habertürk","https://www.haberturk.com/rss"],["Habertürk Gündem","Habertürk","https://www.haberturk.com/rss/kategori/gundem.xml"],["Habertürk Ekonomi","Habertürk","https://www.haberturk.com/rss/ekonomi.xml"],["Haberler.com","Haberler.com","https://rss.haberler.com/RssNew.aspx"],["Sözcü Son Dakika","Sözcü","https://www.sozcu.com.tr/feeds-son-dakika"],["Sözcü Gündem","Sözcü","https://www.sozcu.com.tr/feeds-rss-category-gundem"],["Sözcü Ekonomi","Sözcü","https://www.sozcu.com.tr/feeds-rss-category-ekonomi"],["Hürriyet","Hürriyet","https://rss.hurriyet.com.tr/"]
].map(([source,publisher,url])=>({source,publisher,url}));
const STOP=new Set("ve veya ile için bir bu şu o da de mi mı mu mü son dakika haber haberi haberleri yeni göre olarak daha en çok ise var oldu olan ilgili ardından sonra önce bugün türkiye türkiyede açıklama açıkladı dikkat çeken gelişme gelişmeler sıcak flaş".split(" "));
const clean=(s="")=>String(s).replace(/<!\[CDATA\[|\]\]>/g,"").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const compact=(s,n=150)=>{s=String(s||"").replace(/\s+/g," ").trim();return s.length>n?s.slice(0,n-1).trimEnd()+"…":s};
const norm=s=>clean(s).toLocaleLowerCase("tr-TR").replace(/[^a-z0-9çğıöşü ]/gi," ").replace(/\s+/g," ").trim();
const tokens=s=>new Set(norm(s).split(" ").filter(x=>x.length>2&&!STOP.has(x)));
function parse(xml,f){return[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,15).map(m=>{const b=m[1],g=t=>clean(b.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`,`i`))?.[1]||"");return{title:g("title"),description:g("description"),link:g("link")||g("guid"),pubDate:g("pubDate")||g("dc:date")||g("date"),source:f.source,publisher:f.publisher}})}
async function schema(env){await env.DB.batch([env.DB.prepare("CREATE TABLE IF NOT EXISTS worker_state(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS news_queue(fingerprint TEXT PRIMARY KEY,title TEXT NOT NULL,source_url TEXT,primary_source TEXT NOT NULL,sources TEXT NOT NULL,source_count INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'ready',first_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS news_content(fingerprint TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT,hashtags TEXT,visual_prompt TEXT,ai_model TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)")])}
async function getState(env,k){return(await env.DB.prepare("SELECT value FROM worker_state WHERE key=?").bind(k).first())?.value??null}async function setState(env,k,v){await env.DB.prepare("INSERT INTO worker_state(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(k,String(v)).run()}
function score(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;const r=n/Math.min(A.size,B.size);return n>=3&&r>=.38?Math.max(.60,r):n>=2&&r>=.50?Math.max(.56,r):r}
function clusters(items){const out=[];for(const i of items){let best=null,bs=0;for(const c of out){let s=0;for(const x of c.items)s=Math.max(s,score(i.title,x.title));if(s>bs){bs=s;best=c}}if(best&&bs>=.52){best.items.push(i);best.publishers.add(i.publisher);if(new Date(i.pubDate)>new Date(best.primary.pubDate))best.primary=i}else out.push({primary:i,items:[i],publishers:new Set([i.publisher])})}return out.filter(x=>x.publishers.size>=2).sort((a,b)=>new Date(b.primary.pubDate)-new Date(a.primary.pubDate))}
async function fp(c){const count=new Map();for(const i of c.items)for(const t of tokens(i.title))count.set(t,(count.get(t)||0)+1);let a=[...count].filter(([,n])=>n>=2).map(([t])=>t).sort();if(a.length<2)a=[...tokens(c.primary.title)].sort().slice(0,6);const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(a.slice(0,8).join("|")));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("").slice(0,48)}
async function feeds(){return Promise.all(FEEDS.map(async f=>{try{const r=await fetch(f.url,{headers:{"User-Agent":"90Gundem/1.0",Accept:"application/rss+xml, application/xml, text/xml;q=0.9, */*;q=0.5"}});return{...f,ok:r.ok,status:r.status,items:r.ok?parse(await r.text(),f):[]}}catch(e){return{...f,ok:false,status:0,items:[],error:String(e)}}}))}
function tags(item){if(item.ai_hashtags?.length)return item.ai_hashtags.join(" ");const n=norm(item.title+" "+(item.description||"")),h=["#SonDakika","#Gündem"],r=[["erdoğan","#Erdoğan"],["cumhurbaşkanı","#Cumhurbaşkanı"],["galatasaray","#Galatasaray"],["fenerbahçe","#Fenerbahçe"],["beşiktaş","#Beşiktaş"],["trabzonspor","#Trabzonspor"],["futbol","#Futbol"],["emekli","#Emeklilik"],["eyt","#EYT"],["kpss","#KPSS"],["deprem","#Deprem"],["ekonomi","#Ekonomi"],["altın","#Altın"],["dolar","#Dolar"],["sağlık","#Sağlık"],["teknoloji","#Teknoloji"]];for(const[k,v]of r)if(n.includes(k)&&!h.includes(v))h.push(v);return h.slice(0,7).join(" ")}
function share(item){let s=`🔴 SON DAKİKA | ${compact(item.title,105)}\n\n${compact(item.description,135)}\n\n${tags(item)}`;if(s.length>280)s=`🔴 ${compact(item.title,115)}\n\n${compact(item.description,85)}\n\n${tags(item)}`;return s.slice(0,280)}
const esc=(v="")=>String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function html(item){return `<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;width:1080px;height:1080px;overflow:hidden;font-family:Arial,sans-serif;background:#090b10;color:white}.c{width:1080px;height:1080px;padding:64px;background:radial-gradient(circle at 85% 12%,#501018 0,#17131a 26%,#090b10 58%);position:relative}.top{display:flex;align-items:center;gap:24px}.logo{width:118px;height:118px;border-radius:60px;background:#e41f2b;display:flex;align-items:center;justify-content:center;font-size:48px;font-weight:900}.brand{font-size:56px;font-weight:900}.brand b{color:#e41f2b}.breaking{margin-top:62px;display:inline-block;background:#e41f2b;padding:14px 28px;border-radius:10px;font-size:28px;font-weight:800;letter-spacing:2px}.title{font-size:60px;line-height:1.08;font-weight:900;margin-top:28px;max-height:260px;overflow:hidden}.line{width:170px;height:8px;background:#e41f2b;margin:32px 0}.desc{font-size:31px;line-height:1.42;color:#e6e6e8;max-height:230px;overflow:hidden}.footer{position:absolute;left:64px;right:64px;bottom:58px;border-top:1px solid #555;padding-top:24px;display:flex;justify-content:space-between;font-size:24px;color:#bbb}.verified{color:white;font-weight:700}</style></head><body><div class="c"><div class="top"><div class="logo">90+</div><div class="brand"><b>+90</b> GÜNDEM</div></div><div class="breaking">SON DAKİKA</div><div class="title">${esc(item.title)}</div><div class="line"></div><div class="desc">${esc(item.description)}</div><div class="footer"><span class="verified">Doğrulanmış Haber</span><span>90+ GÜNDEM</span></div></div></body></html>`}
async function png(env,item){if(!env.BROWSER)throw new Error("BROWSER binding missing");const r=await env.BROWSER.quickAction("screenshot",{html:html(item),viewport:{width:1080,height:1080},screenshotOptions:{type:"png",fullPage:false}});if(!r.ok)throw new Error(`browser_screenshot_${r.status}:${await r.text()}`);return new Uint8Array(await r.arrayBuffer())}
async function chatId(env){return env.TELEGRAM_CHAT_ID||await getState(env,"telegram_chat_id")}async function tg(env,method,body){const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!j.ok)throw new Error(`telegram_${method}:${JSON.stringify(j).slice(0,250)}`);return j.result}
async function sendPhoto(env,item){const id=await chatId(env);if(!id||!env.TELEGRAM_BOT_TOKEN)return false;const bytes=await png(env,item),form=new FormData();form.append("chat_id",String(id));form.append("photo",new Blob([bytes],{type:"image/png"}),`90gundem-${item.fp}.png`);form.append("caption",`📰 +90 GÜNDEM\n\n${compact(item.title,180)}\n\n${compact(item.description,420)}\n\nKaynaklar: ${item.sources.join(" • ")}\nDoğrulama: ${item.sources.length} bağımsız yayıncı\n\n${tags(item)}`);form.append("reply_markup",JSON.stringify({inline_keyboard:[[{text:"𝕏 TEK TUŞLA PAYLAŞ",url:`https://twitter.com/intent/tweet?text=${encodeURIComponent(share(item))}`}]]}));const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendPhoto`,{method:"POST",body:form}),j=await r.json();if(!j.ok)throw new Error(`telegram_sendPhoto:${JSON.stringify(j).slice(0,250)}`);return true}
async function latest(maxAge=60){const f=await feeds(),all=f.flatMap(x=>x.items),now=Date.now(),fresh=all.filter(i=>{const t=new Date(i.pubDate).getTime(),a=now-t;return i.title&&Number.isFinite(t)&&a>=0&&a<=maxAge*60000}).sort((a,b)=>new Date(b.pubDate)-new Date(a.pubDate));return{f,all,fresh,c:clusters(fresh)}}
async function scan(env,maxAge=null,mode="scheduled"){await schema(env);const d=await latest(maxAge??Number(env.X_MAX_AGE_MINUTES||3));let notified=0,aiUsed=0,skipped=0,lastError=null;for(const c of d.c.slice(0,5)){const fingerprint=await fp(c),sources=[...c.publishers],old=await env.DB.prepare("SELECT status FROM news_queue WHERE fingerprint=?").bind(fingerprint).first();if(old){skipped++;await env.DB.prepare("UPDATE news_queue SET sources=?,source_count=?,last_seen=CURRENT_TIMESTAMP WHERE fingerprint=?").bind(JSON.stringify(sources),sources.length,fingerprint).run();continue}let item=c.primary;try{if(env.OPENROUTER_API_KEY)item=await enrichNews(env,c);if(item.ai_used)aiUsed++}catch(e){lastError=`AI:${String(e?.message||e)}`}
item={...item,fp:fingerprint,sources};await env.DB.prepare("INSERT INTO news_queue(fingerprint,title,source_url,primary_source,sources,source_count,status) VALUES(?,?,?,?,?,?,'ready')").bind(fingerprint,item.title,item.link||c.primary.link,c.primary.source,JSON.stringify(sources),sources.length).run();await env.DB.prepare("INSERT OR REPLACE INTO news_content(fingerprint,title,description,hashtags,visual_prompt,ai_model,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)").bind(fingerprint,item.title,item.description||"",JSON.stringify(item.ai_hashtags||[]),item.visual_prompt||"",item.ai_model||"").run();try{if(await sendPhoto(env,item)){await env.DB.prepare("UPDATE news_queue SET status='share_ready' WHERE fingerprint=?").bind(fingerprint).run();notified++}}catch(e){lastError=String(e?.message||e)}}const state={at:new Date().toISOString(),mode,max_age_minutes:maxAge??Number(env.X_MAX_AGE_MINUTES||3),matching:"png-newsroom-v4",fetched:d.all.length,fresh:d.fresh.length,verified:d.c.length,new_items:d.c.length-skipped,dedupe_skipped:skipped,openrouter_configured:Boolean(env.OPENROUTER_API_KEY),ai_used:aiUsed,telegram_ready:Boolean(env.TELEGRAM_BOT_TOKEN&&await chatId(env)),telegram_notified:notified,telegram_media:"photo-png",approval_required:false,x_api_publishing:false,lastError};await setState(env,"last_scan",JSON.stringify(state));return state}
async function setup(env){if(!env.TELEGRAM_BOT_TOKEN)return Response.json({status:"error",error:"TELEGRAM_BOT_TOKEN missing"},{status:500});if(await chatId(env))return Response.json({status:"already_configured",telegram_ready:true});const u=await tg(env,"getUpdates",{limit:20,timeout:0,allowed_updates:["message"]}),s=u.filter(x=>x.message?.chat?.type==="private"&&String(x.message?.text||"").trim().startsWith("/start"));if(!s.length)return Response.json({status:"waiting",message:"Bota /start gönderip tekrar aç."});await setState(env,"telegram_chat_id",String(s.at(-1).message.chat.id));return Response.json({status:"configured",telegram_ready:true})}
export default{async fetch(req,env){await schema(env);const u=new URL(req.url);if(u.pathname==="/image-test"){try{return new Response(await png(env,{title:"+90 GÜNDEM görsel sistemi aktif",description:"Doğrulanmış haberler yapay zeka editöründen geçerek markalı görsel kart halinde hazırlanacak."}),{headers:{"Content-Type":"image/png","Cache-Control":"no-store"}})}catch(e){return Response.json({status:"error",browser_binding:Boolean(env.BROWSER),error:String(e?.message||e)},{status:500})}}if(u.pathname==="/telegram-setup")return setup(env);if(u.pathname==="/run-once"){try{return Response.json({status:"ok",...await scan(env,60,"manual-png-test")})}catch(e){return Response.json({status:"error",error:String(e?.message||e)},{status:500})}}if(u.pathname==="/telegram-test"){try{const d=await latest(60),c=d.c[0];if(!c)return Response.json({status:"ok",sent:false,message:"Doğrulanmış haber yok."});let item=env.OPENROUTER_API_KEY?await enrichNews(env,c):c.primary;item={...item,fp:await fp(c),sources:[...c.publishers]};return Response.json({status:"ok",sent:await sendPhoto(env,item),title:item.title})}catch(e){return Response.json({status:"error",error:String(e?.message||e)},{status:500})}}if(u.pathname==="/health")return Response.json({status:"ok",service:"90gundem-cloudflare",version:"png-newsroom-v4",feeds:FEEDS.length,browser_binding:Boolean(env.BROWSER),openrouter_configured:Boolean(env.OPENROUTER_API_KEY),telegram_ready:Boolean(env.TELEGRAM_BOT_TOKEN&&await chatId(env)),telegram_media:"photo-png",approval_required:false,x_api_publishing:false});if(u.pathname==="/status"){const s=await getState(env,"last_scan");return Response.json({status:"ok",last_scan:s?JSON.parse(s):null})}return new Response("90+ GUNDEM Cloudflare Worker")},async scheduled(c,env,ctx){ctx.waitUntil(scan(env,null,"scheduled").catch(e=>setState(env,"last_scan",JSON.stringify({at:new Date().toISOString(),fatalError:String(e?.message||e)}))))}};