import v9 from './index-v9.js';

// V10 expands discovery telemetry to 30 high-signal Turkish news feeds.
// The proven publishing pipeline remains unchanged; candidates are admitted only after health/freshness checks.
const FEEDS=[
['TRT Son Dakika','https://www.trthaber.com/sondakika_articles.rss'],['TRT Manşet','https://www.trthaber.com/manset_articles.rss'],['TRT Gündem','https://www.trthaber.com/gundem_articles.rss'],['TRT Türkiye','https://www.trthaber.com/turkiye_articles.rss'],['TRT Dünya','https://www.trthaber.com/dunya_articles.rss'],['TRT Ekonomi','https://www.trthaber.com/ekonomi_articles.rss'],['TRT Sağlık','https://www.trthaber.com/saglik_articles.rss'],['TRT Bilim Teknoloji','https://www.trthaber.com/bilim_teknoloji_articles.rss'],['TRT Güncel','https://www.trthaber.com/guncel_articles.rss'],
['Habertürk Genel','https://www.haberturk.com/rss'],['Habertürk Manşet','https://www.haberturk.com/rss/manset.xml'],['Habertürk Gündem','https://www.haberturk.com/rss/kategori/gundem.xml'],['Habertürk Siyaset','https://www.haberturk.com/rss/kategori/siyaset.xml'],['Habertürk Dünya','https://www.haberturk.com/rss/kategori/dunya.xml'],['Habertürk Ekonomi','https://www.haberturk.com/rss/ekonomi.xml'],['Habertürk Sağlık','https://www.haberturk.com/rss/kategori/saglik.xml'],['Habertürk Teknoloji','https://www.haberturk.com/rss/kategori/teknoloji.xml'],
['Sözcü Son Dakika','https://www.sozcu.com.tr/feeds-son-dakika'],['Sözcü Gündem','https://www.sozcu.com.tr/feeds-rss-category-gundem'],['Sözcü Ekonomi','https://www.sozcu.com.tr/feeds-rss-category-ekonomi'],['Haberler.com','https://rss.haberler.com/RssNew.aspx'],
['NTV Son Dakika','https://www.ntv.com.tr/son-dakika.rss'],['NTV Gündem','https://www.ntv.com.tr/gundem.rss'],['NTV Türkiye','https://www.ntv.com.tr/turkiye.rss'],['NTV Dünya','https://www.ntv.com.tr/dunya.rss'],['NTV Ekonomi','https://www.ntv.com.tr/ekonomi.rss'],
['CNN Türk Genel','https://www.cnnturk.com/feed/rss/all/news'],['Sabah Ana Sayfa','https://www.sabah.com.tr/rss/anasayfa.xml'],['Cumhuriyet Son Dakika','https://www.cumhuriyet.com.tr/rss/son_dakika.xml'],['Milliyet Gündem','https://www.milliyet.com.tr/rss/rssnew/gundemrss.xml']
].map(([name,url])=>({name,url}));
const decode=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&apos;|&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
function dateValue(block){const patterns=[/<pubDate[^>]*>([\s\S]*?)<\/pubDate>/i,/<dc:date[^>]*>([\s\S]*?)<\/dc:date>/i,/<date[^>]*>([\s\S]*?)<\/date>/i,/<published[^>]*>([\s\S]*?)<\/published>/i,/<updated[^>]*>([\s\S]*?)<\/updated>/i];for(const p of patterns){const m=block.match(p);if(!m)continue;const raw=decode(m[1]);let t=Date.parse(raw);if(!Number.isFinite(t)){const tr=raw.match(/(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})\s*(\d{1,2})?[:.]?(\d{2})?/);if(tr)t=Date.parse(`${tr[3]}-${tr[2].padStart(2,'0')}-${tr[1].padStart(2,'0')}T${(tr[4]||'00').padStart(2,'0')}:${tr[5]||'00'}:00+03:00`)}if(Number.isFinite(t))return t}return 0}
function inspect(xml){const itemBlocks=[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(x=>x[1]);const entryBlocks=itemBlocks.length?[]:[...xml.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)].map(x=>x[1]);const blocks=(itemBlocks.length?itemBlocks:entryBlocks).slice(0,40);let latest=0,title=null;for(const b of blocks){const t=dateValue(b);if(t>latest){latest=t;title=decode(b.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'')}}const age=latest?Math.max(0,Math.round((Date.now()-latest)/60000)):null;let quality=0;if(blocks.length)quality+=30;if(age!==null){if(age<=15)quality+=50;else if(age<=60)quality+=40;else if(age<=180)quality+=25;else if(age<=720)quality+=10}return{items:blocks.length,latest_age_minutes:age,latest_title:title,live_3h:age!==null&&age<=180,quality_score:quality}}
async function probe(){const results=await Promise.all(FEEDS.map(async s=>{const st=Date.now();try{const r=await fetch(s.url,{headers:{'User-Agent':'90Gundem/4.0',Accept:'application/rss+xml, application/atom+xml, application/xml, text/xml;q=0.9, */*;q=0.5'},redirect:'follow'});const xml=r.ok?await r.text():'';const q=inspect(xml),lat=Date.now()-st;return{name:s.name,ok:r.ok,status:r.status,latency_ms:lat,...q,quality_score:Math.max(0,q.quality_score+(lat<300?20:lat<1000?10:0))}}catch(e){return{name:s.name,ok:false,status:0,latency_ms:Date.now()-st,items:0,latest_age_minutes:null,latest_title:null,live_3h:false,quality_score:0,error:String(e)}}}));results.sort((a,b)=>b.quality_score-a.quality_score||a.latency_ms-b.latency_ms);return{configured:results.length,http_online:results.filter(x=>x.ok).length,producing:results.filter(x=>x.items>0).length,live_3h:results.filter(x=>x.live_3h).length,excellent:results.filter(x=>x.quality_score>=90).length,results}}
export default {async fetch(req,env,ctx){const u=new URL(req.url);if(u.pathname==='/health'){const r=await v9.fetch(req,env,ctx);let d={};try{d=await r.clone().json()}catch{}return Response.json({...d,version:'fast-news-v10',discovery_feeds:FEEDS.length,source_quality_scoring:true,source_date_parser_v2:true})}if(u.pathname==='/source-health')return Response.json({status:'ok',version:'fast-news-v10',...(await probe())});return v9.fetch(req,env,ctx)},async scheduled(event,env,ctx){return v9.scheduled(event,env,ctx)}};
