const FEEDS=[
 {source:"TRT Haber",publisher:"TRT Haber",url:"https://www.trthaber.com/sondakika_articles.rss"},
 {source:"TRT Gündem",publisher:"TRT Haber",url:"https://www.trthaber.com/gundem_articles.rss"},
 {source:"Habertürk",publisher:"Habertürk",url:"https://www.haberturk.com/rss"},
 {source:"Habertürk Gündem",publisher:"Habertürk",url:"https://www.haberturk.com/rss/kategori/gundem.xml"},
 {source:"Habertürk Ekonomi",publisher:"Habertürk",url:"https://www.haberturk.com/rss/ekonomi.xml"},
 {source:"Haberler.com",publisher:"Haberler.com",url:"https://rss.haberler.com/RssNew.aspx"}
];
const STOP=new Set("ve veya ile için bir bu şu o da de mi mı mu mü son dakika haber haberi haberleri yeni göre olarak daha en çok ise var oldu olan ilgili ardından sonra önce bugün türkiye türkiyede açıklama açıkladı dikkat çeken gelişme gelişmeler sıcak flaş".split(" "));
function decodeXml(s=""){return s.replace(/<!\[CDATA\[|\]\]>/g,"").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&apos;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");}
function items(xml,f){return [...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,15).map(m=>{const x=m[1];const get=t=>decodeXml((x.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`,"i"))||[])[1]||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();return{title:get("title"),link:get("link")||get("guid"),pubDate:get("pubDate")||get("dc:date")||get("date"),source:get("source")||f.source,publisher:f.publisher};});}
async function ensureSchema(env){await env.DB.batch([env.DB.prepare("CREATE TABLE IF NOT EXISTS worker_state (key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS news_queue (fingerprint TEXT PRIMARY KEY,title TEXT NOT NULL,source_url TEXT,primary_source TEXT NOT NULL,sources TEXT NOT NULL,source_count INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'ready',first_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_news_queue_status ON news_queue(status,last_seen)")]);}
async function stateGet(env,key){const r=await env.DB.prepare("SELECT value FROM worker_state WHERE key=?").bind(key).first();return r?.value??null;}
async function stateSet(env,key,value){await env.DB.prepare("INSERT INTO worker_state(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(key,String(value)).run();}
function normalizeTitle(text){return text.toLocaleLowerCase("tr-TR").replace(/[^a-z0-9çğıöşü ]/gi," ").replace(/\s+/g," ").trim();}
function tokenList(text){return normalizeTitle(text).split(" ").filter(x=>x.length>2&&!STOP.has(x));}
function tokens(text){return new Set(tokenList(text));}
function numbers(text){return new Set((normalizeTitle(text).match(/\b\d+(?:[.,]\d+)?\b/g)||[]));}
function caps(text){return new Set((String(text).match(/(?:^|\s)([A-ZÇĞİÖŞÜ][a-zçğıöşü]{2,}(?:\s+[A-ZÇĞİÖŞÜ][a-zçğıöşü]{2,})*)/g)||[]).map(x=>normalizeTitle(x)));}
function overlap(A,B){if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.min(A.size,B.size);}
function eventScore(a,b){const A=tokens(a),B=tokens(b),lex=overlap(A,B);let shared=0;for(const x of A)if(B.has(x))shared++;const num=overlap(numbers(a),numbers(b)),proper=overlap(caps(a),caps(b));const strong=(proper>=.5&&shared>=2)||(num===1&&shared>=2)||(shared>=3&&lex>=.38);return strong?Math.max(lex,.56+proper*.16+num*.12):lex;}
async function hash(text){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function eventFingerprint(c){const sets=c.items.map(x=>tokens(x.title));const counts=new Map();for(const s of sets)for(const x of s)counts.set(x,(counts.get(x)||0)+1);let shared=[...counts].filter(([,n])=>n>=2).map(([x])=>x).sort();if(shared.length<2)shared=tokenList(c.primary.title).sort().slice(0,6);return hash(shared.slice(0,8).join("|"));}
function shareText(n){let title=n.title.replace(/\s+-\s+[^-]{2,60}$/,"").trim();const suffix="\n\n#SonDakika #Gündem";if(title.length>280-suffix.length)title=title.slice(0,280-suffix.length-1).trimEnd()+"…";return title+suffix;}
function xIntent(n){return `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText(n))}`;}
async function tg(env,method,body={}){if(!env.TELEGRAM_BOT_TOKEN)throw new Error("missing_TELEGRAM_BOT_TOKEN");const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!j.ok)throw new Error(`telegram_${method}:${JSON.stringify(j).slice(0,300)}`);return j.result;}
async function telegramChatId(env){return env.TELEGRAM_CHAT_ID||await stateGet(env,"telegram_chat_id");}
async function telegramReady(env){return Boolean(env.TELEGRAM_BOT_TOKEN&&await telegramChatId(env));}
async function notifyTelegram(env,n){const chat=await telegramChatId(env);if(!chat)return false;const text=`📰 +90 GÜNDEM ONAY\n\n${n.title}\n\nKaynaklar: ${n.sources.join(" • ")}\nDoğrulama: ${n.sources.length} bağımsız yayıncı`;await tg(env,"sendMessage",{chat_id:chat,text,disable_web_page_preview:true,reply_markup:{inline_keyboard:[[{text:"✅ ONAYLA",callback_data:`approve:${n.fp}`},{text:"❌ REDDET",callback_data:`reject:${n.fp}`}]]}});return true;}
async function answerCb(env,id,text){try{await tg(env,"answerCallbackQuery",{callback_query_id:id,text});}catch{}}
async function setupTelegram(request,env){if(!env.TELEGRAM_BOT_TOKEN)return Response.json({status:"error",error:"TELEGRAM_BOT_TOKEN missing"},{status:500});const existing=await telegramChatId(env);if(existing)return Response.json({status:"already_configured",telegram_ready:true,message:"Telegram zaten bu Worker'a kilitli."});const updates=await tg(env,"getUpdates",{limit:20,timeout:0,allowed_updates:["message"]});const starts=(updates||[]).filter(x=>x.message?.chat?.type==="private"&&String(x.message?.text||"").trim().startsWith("/start"));if(!starts.length)return Response.json({status:"waiting",telegram_ready:false,message:"Telegram botuna /start gönderip bu sayfayı tekrar aç."});const last=starts[starts.length-1],chat=String(last.message.chat.id);await stateSet(env,"telegram_chat_id",chat);const origin=new URL(request.url).origin,secret=crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","");await stateSet(env,"telegram_webhook_secret",secret);await tg(env,"setWebhook",{url:`${origin}/telegram/webhook`,secret_token:secret,allowed_updates:["callback_query"],drop_pending_updates:true});await tg(env,"sendMessage",{chat_id:chat,text:"✅ +90 GÜNDEM bağlantısı tamamlandı.\n\nDoğrulanan haberler buraya onay için gelecek. X API kullanılmayacak."});return Response.json({status:"configured",telegram_ready:true,webhook_ready:true});}
async function handleTelegram(request,env){const chat=await telegramChatId(env),secret=env.TELEGRAM_WEBHOOK_SECRET||await stateGet(env,"telegram_webhook_secret");if(!secret||request.headers.get("X-Telegram-Bot-Api-Secret-Token")!==secret)return new Response("forbidden",{status:403});const u=await request.json(),q=u.callback_query;if(!q?.data)return Response.json({ok:true});if(!chat||String(q.message?.chat?.id)!==String(chat)){await answerCb(env,q.id,"Yetkisiz sohbet");return Response.json({ok:true});}const [action,fp]=q.data.split(":"),row=await env.DB.prepare("SELECT * FROM news_queue WHERE fingerprint=?").bind(fp).first();if(!row){await answerCb(env,q.id,"Haber bulunamadı");return Response.json({ok:true});}if(action==="reject"){await env.DB.prepare("UPDATE news_queue SET status='rejected',last_seen=CURRENT_TIMESTAMP WHERE fingerprint=?").bind(fp).run();await tg(env,"editMessageReplyMarkup",{chat_id:q.message.chat.id,message_id:q.message.message_id,reply_markup:{inline_keyboard:[]}});await answerCb(env,q.id,"Reddedildi");return Response.json({ok:true});}if(action==="approve"){await env.DB.prepare("UPDATE news_queue SET status='approved',last_seen=CURRENT_TIMESTAMP WHERE fingerprint=?").bind(fp).run();await tg(env,"editMessageReplyMarkup",{chat_id:q.message.chat.id,message_id:q.message.message_id,reply_markup:{inline_keyboard:[[{text:"𝕏 X'te Paylaş",url:xIntent({title:row.title})}]]}});await answerCb(env,q.id,"Onaylandı — X'te Paylaş'a dokun");return Response.json({ok:true});}return Response.json({ok:true});}
async function saveState(env,state){await stateSet(env,"last_scan",JSON.stringify(state));}
async function fetchFeeds(){return Promise.all(FEEDS.map(async f=>{try{const r=await fetch(f.url,{headers:{"User-Agent":"90Gundem/1.0","Accept":"application/rss+xml, application/xml, text/xml;q=0.9, */*;q=0.5"}});if(!r.ok)return{...f,ok:false,status:r.status,items:[]};return{...f,ok:true,status:r.status,items:items(await r.text(),f)};}catch(e){return{...f,ok:false,status:0,error:String(e?.message||e),items:[]};}}));}
function verifiedClusters(fresh,threshold=.52){const clusters=[];for(const n of fresh){let best=null,bestScore=0;for(const c of clusters){let score=0;for(const old of c.items)score=Math.max(score,eventScore(n.title,old.title));if(score>bestScore){bestScore=score;best=c;}}if(best&&bestScore>=threshold){best.items.push(n);best.publishers.add(n.publisher);if(new Date(n.pubDate)>new Date(best.primary.pubDate))best.primary=n;}else clusters.push({primary:n,items:[n],publishers:new Set([n.publisher])});}return clusters.filter(c=>c.publishers.size>=2).sort((a,b)=>new Date(b.primary.pubDate)-new Date(a.primary.pubDate));}
async function queueCluster(env,c){const fp=await eventFingerprint(c),sources=[...c.publishers],existing=await env.DB.prepare("SELECT status FROM news_queue WHERE fingerprint=?").bind(fp).first();if(existing){await env.DB.prepare("UPDATE news_queue SET sources=?,source_count=?,last_seen=CURRENT_TIMESTAMP WHERE fingerprint=?").bind(JSON.stringify(sources),sources.length,fp).run();return{...c.primary,fp,sources,isNew:false,status:existing.status};}await env.DB.prepare("INSERT INTO news_queue(fingerprint,title,source_url,primary_source,sources,source_count,status) VALUES(?,?,?,?,?,?,'ready')").bind(fp,c.primary.title,c.primary.link,c.primary.source,JSON.stringify(sources),sources.length).run();return{...c.primary,fp,sources,isNew:true,status:"ready"};}
async function scan(env,maxAgeOverride=null,mode="scheduled"){await ensureSchema(env);const maxAge=(maxAgeOverride??Number(env.X_MAX_AGE_MINUTES||3))*60000,now=Date.now(),feeds=await fetchFeeds(),all=feeds.flatMap(f=>f.items);const fresh=all.filter(x=>{const ts=new Date(x.pubDate).getTime(),age=now-ts;return x.title&&Number.isFinite(ts)&&age>=0&&age<=maxAge;}).sort((a,b)=>new Date(b.pubDate)-new Date(a.pubDate));const verified=verifiedClusters(fresh,Number(env.NEWS_TITLE_SIMILARITY||.52)),queued=[];let notified=0,lastError=null;for(const c of verified.slice(0,5)){const n=await queueCluster(env,c);queued.push(n);if(n.isNew&&await telegramReady(env)){try{if(await notifyTelegram(env,n)){await env.DB.prepare("UPDATE news_queue SET status='pending_approval',last_seen=CURRENT_TIMESTAMP WHERE fingerprint=?").bind(n.fp).run();notified++;}}catch(e){lastError=String(e?.message||e);}}
const state={at:new Date().toISOString(),mode,max_age_minutes:maxAge/60000,feed_status:feeds.map(f=>({source:f.source,ok:f.ok,status:f.status,items:f.items.length})),fetched:all.length,fresh:fresh.length,verified:verified.length,queued:queued.length,telegram_ready:await telegramReady(env),telegram_notified:notified,x_api_publishing:false,matching:"event-v2",lastError};await saveState(env,state);return state;}
export default{async fetch(request,env){const u=new URL(request.url);await ensureSchema(env);if(u.pathname==="/telegram-setup"&&request.method==="GET")return setupTelegram(request,env);if(u.pathname==="/telegram/webhook"&&request.method==="POST")return handleTelegram(request,env);if(u.pathname==="/health")return Response.json({status:"ok",service:"90gundem-cloudflare",feeds:FEEDS.length,verification:"2-distinct-publishers-event-v2",telegram_ready:await telegramReady(env),x_api_publishing:false});if(u.pathname==="/status"){const raw=await stateGet(env,"last_scan"),q=await env.DB.prepare("SELECT status,COUNT(*) n FROM news_queue GROUP BY status").all();return Response.json({status:"ok",queue:Object.fromEntries((q.results||[]).map(x=>[x.status,Number(x.n)])),last_scan:raw?JSON.parse(raw):null});}if(u.pathname==="/run-once"){try{return Response.json({status:"ok",...await scan(env,60,"manual-verification-test")});}catch(e){return Response.json({status:"error",error:String(e?.message||e)},{status:500});}}return new Response("90+ GUNDEM Cloudflare Worker",{status:200});},async scheduled(controller,env,ctx){ctx.waitUntil(scan(env,null,"scheduled").catch(e=>saveState(env,{at:new Date().toISOString(),fatalError:String(e?.message||e)}).catch(()=>{})));}};