import v10 from './index-v10.js';

// V11 production fast-discovery gate. The existing verified publisher engine remains
// responsible for AI/card/Telegram delivery; this layer continuously scans the
// expanded 30-feed pool and persists fresh high-signal candidates for correlation.
const FEEDS=[
['TRT Son Dakika','TRT Haber','https://www.trthaber.com/sondakika_articles.rss'],['TRT Manşet','TRT Haber','https://www.trthaber.com/manset_articles.rss'],['TRT Gündem','TRT Haber','https://www.trthaber.com/gundem_articles.rss'],['TRT Türkiye','TRT Haber','https://www.trthaber.com/turkiye_articles.rss'],['TRT Dünya','TRT Haber','https://www.trthaber.com/dunya_articles.rss'],['TRT Ekonomi','TRT Haber','https://www.trthaber.com/ekonomi_articles.rss'],['TRT Sağlık','TRT Haber','https://www.trthaber.com/saglik_articles.rss'],['TRT Bilim Teknoloji','TRT Haber','https://www.trthaber.com/bilim_teknoloji_articles.rss'],['TRT Güncel','TRT Haber','https://www.trthaber.com/guncel_articles.rss'],
['Habertürk Genel','Habertürk','https://www.haberturk.com/rss'],['Habertürk Manşet','Habertürk','https://www.haberturk.com/rss/manset.xml'],['Habertürk Gündem','Habertürk','https://www.haberturk.com/rss/kategori/gundem.xml'],['Habertürk Siyaset','Habertürk','https://www.haberturk.com/rss/kategori/siyaset.xml'],['Habertürk Dünya','Habertürk','https://www.haberturk.com/rss/kategori/dunya.xml'],['Habertürk Ekonomi','Habertürk','https://www.haberturk.com/rss/ekonomi.xml'],['Habertürk Sağlık','Habertürk','https://www.haberturk.com/rss/kategori/saglik.xml'],['Habertürk Teknoloji','Habertürk','https://www.haberturk.com/rss/kategori/teknoloji.xml'],
['Sözcü Son Dakika','Sözcü','https://www.sozcu.com.tr/feeds-son-dakika'],['Sözcü Gündem','Sözcü','https://www.sozcu.com.tr/feeds-rss-category-gundem'],['Sözcü Ekonomi','Sözcü','https://www.sozcu.com.tr/feeds-rss-category-ekonomi'],['Haberler.com','Haberler.com','https://rss.haberler.com/RssNew.aspx'],['NTV Son Dakika','NTV','https://www.ntv.com.tr/son-dakika.rss'],['NTV Gündem','NTV','https://www.ntv.com.tr/gundem.rss'],['NTV Türkiye','NTV','https://www.ntv.com.tr/turkiye.rss'],['NTV Dünya','NTV','https://www.ntv.com.tr/dunya.rss'],['NTV Ekonomi','NTV','https://www.ntv.com.tr/ekonomi.rss'],['CNN Türk Genel','CNN Türk','https://www.cnnturk.com/feed/rss/all/news'],['Sabah Ana Sayfa','Sabah','https://www.sabah.com.tr/rss/anasayfa.xml'],['Cumhuriyet Son Dakika','Cumhuriyet','https://www.cumhuriyet.com.tr/rss/son_dakika.xml'],['Milliyet Gündem','Milliyet','https://www.milliyet.com.tr/rss/rssnew/gundemrss.xml']
].map(([source,publisher,url])=>({source,publisher,url}));
const dec=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&apos;|&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const norm=s=>dec(s).toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü ]/gi,' ').replace(/\s+/g,' ').trim();
const SEO=/(kimdir|kaç yaşında|nereli|ne zaman|saat kaçta|hangi kanalda|maç kadrosu|ilk 11|belli oldu mu|deprem mi oldu|son depremler|bugün hangi|yayın akışı|hava durumu|namaz vakti|burç|astroloji|dizi|fragman|bölüm|masterchef|survivor|magazin)/i;
const HARD=/(deprem|yangın|sel|kaza|operasyon|gözalt|tutuk|saldırı|savaş|ateşkes|cumhurbaşkan|bakan|tbmm|meclis|mahkeme|savcı|seçim|enflasyon|faiz|borsa|dolar|euro|altın|asgari ücret|emekli|zam|sağlık|salgın|nato|abd|rusya|ukrayna|israil|gazze|suriye|iran|teknoloji|yapay zeka|siber|milli takım|şampiyon|final|transfer)/i;
function parseDate(b){for(const p of [/<pubDate[^>]*>([\s\S]*?)<\/pubDate>/i,/<dc:date[^>]*>([\s\S]*?)<\/dc:date>/i,/<date[^>]*>([\s\S]*?)<\/date>/i,/<published[^>]*>([\s\S]*?)<\/published>/i,/<updated[^>]*>([\s\S]*?)<\/updated>/i]){const m=b.match(p);if(m){const t=Date.parse(dec(m[1]));if(Number.isFinite(t))return t}}return 0}
function parse(xml,f){return [...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,40).map(m=>{const b=m[1],g=t=>dec(b.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`,'i'))?.[1]||'');return{source:f.source,publisher:f.publisher,title:g('title'),description:g('description'),link:g('link')||g('guid'),ts:parseDate(b)}})}
const words=s=>new Set(norm(s).split(' ').filter(x=>x.length>3));
function similar(a,b){const A=words(a),B=words(b);if(!A.size||!B.size)return false;let n=0;for(const x of A)if(B.has(x))n++;return n>=3&&n/Math.min(A.size,B.size)>=.38}
async function discover(env){const now=Date.now(),responses=await Promise.all(FEEDS.map(async f=>{try{const r=await fetch(f.url,{headers:{'User-Agent':'90Gundem/5.0',Accept:'application/rss+xml, application/xml, text/xml;q=0.9, */*;q=0.5'}});return r.ok?parse(await r.text(),f):[]}catch{return[]}})),all=responses.flat();
 const pool=all.filter(i=>i.ts&&now-i.ts>=0&&now-i.ts<=15*60000&&!SEO.test(`${i.title} ${i.description}`)&&HARD.test(`${i.title} ${i.description}`));
 const primaries=pool.filter(i=>now-i.ts<=3*60000);let verified=[];for(const p of primaries){const pubs=new Set([p.publisher]);for(const x of pool)if(x.publisher!==p.publisher&&similar(p.title,x.title))pubs.add(x.publisher);if(pubs.size>=2)verified.push({title:p.title,publisher:p.publisher,age_seconds:Math.round((now-p.ts)/1000),publishers:pubs.size})}
 // Keep only a compact operational snapshot; public posts never expose source names.
 const snap={at:new Date().toISOString(),version:'production-fast-v11',feeds:FEEDS.length,items:all.length,verification_pool_15m:pool.length,primary_3m:primaries.length,verified_fast:verified.length,top:verified.slice(0,5).map(x=>({title:x.title,age_seconds:x.age_seconds,publishers:x.publishers}))};
 await env.DB.prepare('CREATE TABLE IF NOT EXISTS worker_state(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)').run();await env.DB.prepare('INSERT INTO worker_state(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind('v11_fast_discovery',JSON.stringify(snap)).run();return snap}
async function getSnap(env){try{return JSON.parse((await env.DB.prepare("SELECT value FROM worker_state WHERE key='v11_fast_discovery'").first())?.value||'null')}catch{return null}}
export default{async fetch(req,env,ctx){const u=new URL(req.url);if(u.pathname==='/health'){const r=await v10.fetch(req,env,ctx);let d={};try{d=await r.clone().json()}catch{}return Response.json({...d,version:'production-fast-v11',production_discovery_feeds:30,primary_freshness_minutes:3,corroboration_window_minutes:15,seo_filter_v2:true,fast_discovery_active:true})}if(u.pathname==='/fast-status')return Response.json({status:'ok',last_fast_discovery:await getSnap(env)});if(u.pathname==='/fast-test')return Response.json({status:'ok',...(await discover(env))});return v10.fetch(req,env,ctx)},async scheduled(event,env,ctx){ctx.waitUntil(discover(env));return v10.scheduled(event,env,ctx)}};
