import v11 from './index-v11.js';

// V12 SPEED-FIRST: trusted publishers can produce an instant candidate without
// waiting for a second publisher. Risky/claim-like stories still require corroboration.
const FEEDS=[
['TRT Son Dakika','TRT Haber',100,'https://www.trthaber.com/sondakika_articles.rss'],['TRT Dünya','TRT Haber',95,'https://www.trthaber.com/dunya_articles.rss'],['TRT Gündem','TRT Haber',95,'https://www.trthaber.com/gundem_articles.rss'],['Habertürk Genel','Habertürk',95,'https://www.haberturk.com/rss'],['Habertürk Gündem','Habertürk',95,'https://www.haberturk.com/rss/kategori/gundem.xml'],['NTV Son Dakika','NTV',95,'https://www.ntv.com.tr/son-dakika.rss'],['NTV Gündem','NTV',90,'https://www.ntv.com.tr/gundem.rss'],['NTV Türkiye','NTV',90,'https://www.ntv.com.tr/turkiye.rss'],['NTV Dünya','NTV',90,'https://www.ntv.com.tr/dunya.rss'],['CNN Türk Genel','CNN Türk',90,'https://www.cnnturk.com/feed/rss/all/news'],['Sabah Ana Sayfa','Sabah',90,'https://www.sabah.com.tr/rss/anasayfa.xml'],['Cumhuriyet Son Dakika','Cumhuriyet',90,'https://www.cumhuriyet.com.tr/rss/son_dakika.xml'],['Milliyet Gündem','Milliyet',90,'https://www.milliyet.com.tr/rss/rssnew/gundemrss.xml'],['Haberler.com','Haberler.com',85,'https://rss.haberler.com/RssNew.aspx']
].map(([source,publisher,trust,url])=>({source,publisher,trust,url}));
const dec=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&apos;|&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const SEO=/(kimdir|kaç yaşında|nereli|ne zaman|saat kaçta|hangi kanalda|maç kadrosu|ilk 11|belli oldu mu|deprem mi oldu|son depremler|bugün hangi|yayın akışı|hava durumu|namaz vakti|burç|astroloji|dizi|fragman|bölüm|masterchef|survivor|magazin)/i;
const RISKY=/(iddia|iddiası|öne sür|söylenti|kulis|kaynaklara göre|henüz doğrulan|doğrulanmadı|sosyal medyada|iddialara göre)/i;
const HARD=/(deprem|yangın|sel|kaza|operasyon|gözalt|tutuk|saldırı|savaş|ateşkes|cumhurbaşkan|bakan|tbmm|meclis|mahkeme|savcı|seçim|enflasyon|faiz|borsa|dolar|euro|altın|asgari ücret|emekli|zam|sağlık|salgın|nato|abd|rusya|ukrayna|israil|gazze|suriye|iran|teknoloji|yapay zeka|siber|milli takım|şampiyon|final|transfer)/i;
function date(b){for(const p of [/<pubDate[^>]*>([\s\S]*?)<\/pubDate>/i,/<dc:date[^>]*>([\s\S]*?)<\/dc:date>/i,/<date[^>]*>([\s\S]*?)<\/date>/i]){const m=b.match(p),t=m?Date.parse(dec(m[1])):NaN;if(Number.isFinite(t))return t}return 0}
function parse(xml,f){return[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,40).map(m=>{const b=m[1],g=t=>dec(b.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`,'i'))?.[1]||'');return{...f,title:g('title'),description:g('description'),link:g('link')||g('guid'),ts:date(b)}})}
const norm=s=>dec(s).toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü ]/gi,' ').replace(/\s+/g,' ').trim(),words=s=>new Set(norm(s).split(' ').filter(x=>x.length>3));
function similar(a,b){const A=words(a),B=words(b);let n=0;for(const x of A)if(B.has(x))n++;return A.size&&B.size&&n>=3&&n/Math.min(A.size,B.size)>=.38}
async function speed(env){const now=Date.now(),parts=await Promise.all(FEEDS.map(async f=>{try{const r=await fetch(f.url,{headers:{'User-Agent':'90Gundem/6.0'}});return r.ok?parse(await r.text(),f):[]}catch{return[]}})),all=parts.flat(),pool=all.filter(i=>i.ts&&now-i.ts>=0&&now-i.ts<=15*60000&&!SEO.test(i.title+' '+i.description)&&HARD.test(i.title+' '+i.description)),fresh=pool.filter(i=>now-i.ts<=3*60000);const candidates=[];
for(const p of fresh){const matches=pool.filter(x=>x.publisher!==p.publisher&&similar(p.title,x.title)),corroborated=matches.length>0,risky=RISKY.test(p.title+' '+p.description),instant=p.trust>=90&&!risky;const accepted=instant||corroborated;if(accepted)candidates.push({title:p.title,age_seconds:Math.round((now-p.ts)/1000),trust:p.trust,decision:instant?'instant_trusted':'corroborated',corroborated});}
const snap={at:new Date().toISOString(),version:'speed-first-v12',feeds:FEEDS.length,primary_3m:fresh.length,accepted:candidates.length,instant:candidates.filter(x=>x.decision==='instant_trusted').length,corroborated:candidates.filter(x=>x.decision==='corroborated').length,risky_requires_verification:true,top:candidates.slice(0,8)};await env.DB.prepare('CREATE TABLE IF NOT EXISTS worker_state(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)').run();await env.DB.prepare('INSERT INTO worker_state(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind('v12_speed_first',JSON.stringify(snap)).run();return snap}
async function snap(env){try{return JSON.parse((await env.DB.prepare("SELECT value FROM worker_state WHERE key='v12_speed_first'").first())?.value||'null')}catch{return null}}
export default{async fetch(req,env,ctx){const u=new URL(req.url);if(u.pathname==='/health'){const r=await v11.fetch(req,env,ctx);let d={};try{d=await r.clone().json()}catch{}return Response.json({...d,version:'speed-first-v12',speed_first:true,instant_trust_threshold:90,risky_requires_verification:true})}if(u.pathname==='/speed-test')return Response.json({status:'ok',...(await speed(env))});if(u.pathname==='/speed-status')return Response.json({status:'ok',last_speed_scan:await snap(env)});return v11.fetch(req,env,ctx)},async scheduled(event,env,ctx){ctx.waitUntil(speed(env));return v11.scheduled(event,env,ctx)}};
