import { enrichNews } from './openrouter.js';

const FEEDS=[
 ['TRT Son Dakika','TRT Haber','https://www.trthaber.com/sondakika_articles.rss'],
 ['TRT Gündem','TRT Haber','https://www.trthaber.com/gundem_articles.rss'],
 ['Habertürk','Habertürk','https://www.haberturk.com/rss'],
 ['Habertürk Gündem','Habertürk','https://www.haberturk.com/rss/kategori/gundem.xml'],
 ['Habertürk Ekonomi','Habertürk','https://www.haberturk.com/rss/ekonomi.xml'],
 ['Haberler','Haberler.com','https://rss.haberler.com/RssNew.aspx'],
 ['Sözcü Son Dakika','Sözcü','https://www.sozcu.com.tr/feeds-son-dakika'],
 ['Sözcü Gündem','Sözcü','https://www.sozcu.com.tr/feeds-rss-category-gundem'],
 ['Sözcü Ekonomi','Sözcü','https://www.sozcu.com.tr/feeds-rss-category-ekonomi']
].map(([source,publisher,url])=>({source,publisher,url}));

const STOP=new Set('ve veya ile için bir bu şu o da de son dakika haber haberi haberleri yeni göre olarak daha en çok ise var oldu olan ilgili ardından sonra önce bugün türkiye açıklama açıkladı gelişme gelişmeler sıcak flaş'.split(' '));
const JUNK=/(dizi|diziler|fragman|bölüm|reyting|tv yayın|yayın akışı|hangi diziler|bu akşam|gönül dağı|masterchef|survivor|magazin|oyuncu kim|burç|astroloji|fal|yemek tarifi|gelinim mutfakta|müge anlı|esra erol|şarkıcı|konser|sinema filmi|netflix|show tv|kanal d|star tv|now tv)/i;
const NEWS=/(deprem|yangın|sel|kaza|operasyon|gözalt|tutuk|bakan|cumhurbaşkan|erdoğan|tbmm|meclis|mahkeme|savcı|valilik|belediye|seçim|ekonomi|enflasyon|faiz|dolar|euro|altın|borsa|asgari ücret|emekli|zam|savaş|saldırı|ateşkes|nato|avrupa birliği|abd|rusya|ukrayna|israil|gazze|iran|suriye|sağlık|salgın|bakanlık|resmi gazete|karar|açıklama|istifa|atama|yasak|grev|final|şampiyon|transfer|milli takım)/i;
const xmlDecode=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const text=s=>xmlDecode(s).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const norm=s=>text(s).toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü ]/gi,' ').replace(/\s+/g,' ').trim();
const toks=s=>new Set(norm(s).split(' ').filter(x=>x.length>2&&!STOP.has(x)));
const compact=(s,n)=>{s=String(s||'').replace(/\s+/g,' ').trim();if(s.length<=n)return s;const cut=s.slice(0,n+1),p=Math.max(cut.lastIndexOf('. '),cut.lastIndexOf('! '),cut.lastIndexOf('? '));if(p>45)return cut.slice(0,p+1);const w=cut.lastIndexOf(' ');return cut.slice(0,w>20?w:n-1).trim()+'…'};
function imageFromBlock(b){for(const p of [/<media:content\b[^>]*url=["']([^"']+)["']/i,/<media:thumbnail\b[^>]*url=["']([^"']+)["']/i,/<enclosure\b[^>]*url=["']([^"']+)["']/i,/<img\b[^>]*src=["']([^"']+)["']/i]){const m=b.match(p);if(m?.[1]&&/^https?:\/\//i.test(xmlDecode(m[1])))return xmlDecode(m[1])}return''}
function parse(xml,f){return[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,18).map(m=>{const b=m[1],g=t=>text(b.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`,'i'))?.[1]||'');return{title:g('title'),description:g('description'),link:g('link')||g('guid'),pubDate:g('pubDate')||g('dc:date')||g('date'),image:imageFromBlock(b),source:f.source,publisher:f.publisher}})}
async function ogImage(url){if(!url)return'';try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; 90Gundem/1.0)'},redirect:'follow'});if(!r.ok)return'';const h=(await r.text()).slice(0,350000);const m=h.match(/<meta[^>]+(?:property|name)=["'](?:og:image|twitter:image(?::src)?)["'][^>]+content=["']([^"']+)["']/i)||h.match(/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["'](?:og:image|twitter:image(?::src)?)["']/i);return m?.[1]?new URL(xmlDecode(m[1]),url).href:''}catch{return''}}
async function ensureImage(i){return i.image?i:{...i,image:await ogImage(i.link)}}
function score(a,b){const A=toks(a),B=toks(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;const r=n/Math.min(A.size,B.size);return n>=3&&r>=.36?Math.max(.6,r):n>=2&&r>=.5?Math.max(.56,r):r}
function clusters(items){const out=[];for(const i of items){let best=null,bs=0;for(const c of out){let s=0;for(const x of c.items)s=Math.max(s,score(i.title,x.title));if(s>bs){bs=s;best=c}}if(best&&bs>=.52){best.items.push(i);best.publishers.add(i.publisher);if(new Date(i.pubDate)>new Date(best.primary.pubDate))best.primary=i}else out.push({primary:i,items:[i],publishers:new Set([i.publisher])})}return out.filter(c=>c.publishers.size>=2).sort((a,b)=>new Date(b.primary.pubDate)-new Date(a.primary.pubDate))}
async function fp(c){const common=new Map();for(const i of c.items)for(const t of toks(i.title))common.set(t,(common.get(t)||0)+1);let a=[...common].filter(([,n])=>n>=2).map(([t])=>t).sort();if(a.length<2)a=[...toks(c.primary.title)].sort().slice(0,6);const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(a.slice(0,8).join('|')));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,48)}
async function schema(env){await env.DB.batch([env.DB.prepare('CREATE TABLE IF NOT EXISTS worker_state(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'),env.DB.prepare("CREATE TABLE IF NOT EXISTS news_queue(fingerprint TEXT PRIMARY KEY,title TEXT NOT NULL,source_url TEXT,primary_source TEXT NOT NULL,sources TEXT NOT NULL,source_count INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'ready',first_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare('CREATE TABLE IF NOT EXISTS news_content(fingerprint TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT,hashtags TEXT,visual_prompt TEXT,ai_model TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)')])}
async function state(env,k,v){if(v!==undefined){await env.DB.prepare('INSERT INTO worker_state(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind(k,String(v)).run();return}return(await env.DB.prepare('SELECT value FROM worker_state WHERE key=?').bind(k).first())?.value??null}
async function fetchFeeds(){return Promise.all(FEEDS.map(async f=>{try{const r=await fetch(f.url,{headers:{'User-Agent':'90Gundem/1.0',Accept:'application/rss+xml, application/xml, text/xml;q=0.9, */*;q=0.5'}});return{...f,ok:r.ok,items:r.ok?parse(await r.text(),f):[]}}catch{return{...f,ok:false,items:[]}}}))}
function worthy(i){const s=`${i.title} ${i.description}`;return !JUNK.test(s)&&NEWS.test(s)}
async function latest(maxAge){const feeds=await fetchFeeds(),all=feeds.flatMap(x=>x.items),now=Date.now();const fresh=all.filter(i=>{const t=new Date(i.pubDate).getTime(),age=now-t;return i.title&&Number.isFinite(t)&&age>=0&&age<=maxAge*60000&&worthy(i)}).sort((a,b)=>new Date(b.pubDate)-new Date(a.pubDate));return{feeds,all,fresh,c:clusters(fresh)}}
function tagArray(i){const n=norm(i.title+' '+i.description),h=['#SonDakika'];for(const[k,v]of [['deprem','#Deprem'],['ekonomi','#Ekonomi'],['erdoğan','#Erdoğan'],['emekli','#Emeklilik'],['dolar','#Dolar'],['altın','#Altın'],['futbol','#Futbol'],['galatasaray','#Galatasaray'],['fenerbahçe','#Fenerbahçe'],['sağlık','#Sağlık'],['teknoloji','#Teknoloji']])if(n.includes(k)&&!h.includes(v))h.push(v);if(h.length<2)h.push('#Gündem');return h.slice(0,3)}
function share(i){const hs=tagArray(i).join(' '),head=`🔴 SON DAKİKA | ${compact(i.title,90)}`;let room=280-head.length-hs.length-4,desc=compact(i.description,Math.max(0,room));let s=desc?`${head}\n\n${desc}\n\n${hs}`:`${head}\n\n${hs}`;while(s.length>280&&desc){desc=compact(desc,Math.max(20,desc.length-12));s=`${head}\n\n${desc}\n\n${hs}`}return s.length<=280?s:`🔴 ${compact(i.title,120)}\n\n${hs}`}
function category(i){const n=norm(i.title+' '+i.description);if(/ekonomi|dolar|altın|borsa|faiz|enflasyon/.test(n))return'EKONOMİ';if(/futbol|voleybol|basketbol|milli takım|galatasaray|fenerbahçe|beşiktaş|trabzonspor/.test(n))return'SPOR';if(/teknoloji|yapay zeka|telefon|internet/.test(n))return'TEKNOLOJİ';if(/sağlık|hastane|doktor|salgın/.test(n))return'SAĞLIK';if(/savaş|gazze|ukrayna|rusya|abd|iran|suriye/.test(n))return'DÜNYA';return'GÜNDEM'}
function card(i){const photo=i.image?`<img class="photo" src="${esc(i.image)}">`:'';const date=new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'}).format(new Date(i.pubDate||Date.now()));return`<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;width:1080px;height:1080px;overflow:hidden;font-family:Arial,sans-serif;background:#07090d;color:white}.c{width:1080px;height:1080px;position:relative;overflow:hidden;background:#080a0f}.photo{position:absolute;inset:0;width:100%;height:690px;object-fit:cover}.shade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.08),rgba(0,0,0,.08) 40%,#080a0f 66%,#080a0f)}.top{position:absolute;top:35px;left:45px;right:45px;display:flex;justify-content:space-between;align-items:center}.brand{display:flex;gap:14px;align-items:center;background:rgba(4,6,9,.84);padding:10px 18px 10px 10px;border-radius:50px}.logo{width:75px;height:75px;border:5px solid #ef233c;border-radius:50%;background:#080a0f;display:flex;align-items:center;justify-content:center;font-size:31px;font-weight:1000;font-style:italic}.logo b{color:#ef233c}.name{font-size:27px;font-weight:1000}.trust{font-size:10px;letter-spacing:3px;color:#ddd}.date{background:rgba(4,6,9,.84);padding:14px 18px;border-radius:10px;font-size:16px;font-weight:800}.panel{position:absolute;left:50px;right:50px;bottom:45px}.badge{display:inline-block;background:#ed1b2e;padding:11px 18px;font-size:18px;font-weight:1000;letter-spacing:1px}.badge em{font-style:normal;color:#ffd43b;margin-left:12px}.title{font-size:52px;line-height:1.03;font-weight:1000;text-transform:uppercase;margin-top:20px;max-height:160px;overflow:hidden}.line{height:7px;width:145px;background:#ed1b2e;margin:20px 0}.desc{font-size:25px;line-height:1.34;color:#eee;max-height:105px;overflow:hidden}.foot{margin-top:30px;padding-top:17px;border-top:1px solid #343943;display:flex;justify-content:space-between;font-size:15px;font-weight:800;color:#c8cbd0}.verified{color:#fff}.handle{color:#ffd43b}</style></head><body><div class="c">${photo}<div class="shade"></div><div class="top"><div class="brand"><div class="logo">90<b>+</b></div><div><div class="name">90+ GÜNDEM</div><div class="trust">HIZLI • DOĞRU • GÜVENİLİR</div></div></div><div class="date">${esc(date)}</div></div><div class="panel"><div class="badge">SON DAKİKA <em>${category(i)}</em></div><div class="title">${esc(i.title)}</div><div class="line"></div><div class="desc">${esc(i.description)}</div><div class="foot"><span class="verified">✓ DOĞRULANMIŞ HABER</span><span class="handle">90+ GÜNDEM • @90plusgndm</span></div></div></div></body></html>`}
async function png(env,i){if(!env.BROWSER)throw new Error('BROWSER binding missing');const r=await env.BROWSER.quickAction('screenshot',{html:card(i),viewport:{width:1080,height:1080},screenshotOptions:{type:'png',fullPage:false}});if(!r.ok)throw new Error(`browser_${r.status}`);return new Uint8Array(await r.arrayBuffer())}
async function chatId(env){return env.TELEGRAM_CHAT_ID||await state(env,'telegram_chat_id')}
async function sendPhoto(env,i){const id=await chatId(env);if(!id||!env.TELEGRAM_BOT_TOKEN)return false;const bytes=await png(env,i),form=new FormData(),x=share(i);form.append('chat_id',String(id));form.append('photo',new Blob([bytes],{type:'image/png'}),`90gundem-${i.fp}.png`);form.append('caption',`🔴 90+ GÜNDEM\n\n${compact(i.title,180)}\n\n${compact(i.description,520)}\n\n${tagArray(i).join(' ')}`);form.append('reply_markup',JSON.stringify({inline_keyboard:[[{text:`𝕏 X’TE PAYLAŞ • ${x.length}/280`,url:`https://twitter.com/intent/tweet?text=${encodeURIComponent(x)}`}]]}));const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendPhoto`,{method:'POST',body:form}),j=await r.json();if(!j.ok)throw new Error(`telegram:${j.description}`);return true}
async function makeItem(env,c){const base=await ensureImage(c.primary);let i=base;try{if(env.OPENROUTER_API_KEY){const ai=await enrichNews(env,c);i={...base,...ai,image:base.image,link:base.link,pubDate:base.pubDate}}}catch{}return i}
async function scan(env,maxAge=null,mode='scheduled'){await schema(env);const age=maxAge??Number(env.X_MAX_AGE_MINUTES||3),d=await latest(age);let notified=0,skipped=0,lastError=null;for(const c of d.c.slice(0,4)){const fingerprint=await fp(c),old=await env.DB.prepare('SELECT status FROM news_queue WHERE fingerprint=?').bind(fingerprint).first();if(old){skipped++;continue}let i=await makeItem(env,c);i={...i,fp:fingerprint,sources:[...c.publishers]};await env.DB.prepare("INSERT INTO news_queue(fingerprint,title,source_url,primary_source,sources,source_count,status) VALUES(?,?,?,?,?,?,'ready')").bind(fingerprint,i.title,i.link||'',c.primary.source,JSON.stringify(i.sources),i.sources.length).run();await env.DB.prepare('INSERT OR REPLACE INTO news_content(fingerprint,title,description,hashtags,visual_prompt,ai_model,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(fingerprint,i.title,i.description||'',JSON.stringify(tagArray(i)),i.visual_prompt||'',i.ai_model||'').run();try{if(await sendPhoto(env,i)){await env.DB.prepare("UPDATE news_queue SET status='share_ready' WHERE fingerprint=?").bind(fingerprint).run();notified++}}catch(e){lastError=String(e?.message||e)}}const s={at:new Date().toISOString(),mode,version:'breaking-only-v7',fetched:d.all.length,breaking_fresh:d.fresh.length,verified:d.c.length,dedupe_skipped:skipped,telegram_notified:notified,lastError};await state(env,'last_scan',JSON.stringify(s));return s}
async function telegramTest(env){const d=await latest(60),c=d.c[0];if(!c)return{status:'ok',sent:false,message:'Son 60 dakikada 2 kaynakla doğrulanan gerçek zamanlı haber yok.'};let i=await makeItem(env,c);i={...i,fp:await fp(c),sources:[...c.publishers]};const x=share(i);return{status:'ok',sent:await sendPhoto(env,i),title:i.title,category:category(i),x_chars:x.length,source_hidden:true,breaking_filter:true}}
export default{async fetch(req,env){await schema(env);const p=new URL(req.url).pathname;if(p==='/telegram-test'){try{return Response.json(await telegramTest(env))}catch(e){return Response.json({status:'error',error:String(e?.message||e)},{status:500})}}if(p==='/run-once'){try{return Response.json({status:'ok',...await scan(env,60,'manual')})}catch(e){return Response.json({status:'error',error:String(e?.message||e)},{status:500})}}if(p==='/health')return Response.json({status:'ok',service:'90gundem-cloudflare',version:'breaking-only-v7',active:true,cron:'every 2 minutes',max_age_minutes:Number(env.X_MAX_AGE_MINUTES||3),source_names_public:false,entertainment_filter:true,openrouter_configured:Boolean(env.OPENROUTER_API_KEY),telegram_ready:Boolean(env.TELEGRAM_BOT_TOKEN&&await chatId(env)),x_api_publishing:false});if(p==='/status'){const s=await state(env,'last_scan');return Response.json({status:'ok',last_scan:s?JSON.parse(s):null})}return new Response('90+ GUNDEM • BREAKING NEWS V7 • ACTIVE')},async scheduled(c,env,ctx){ctx.waitUntil(scan(env,null,'scheduled').catch(e=>state(env,'last_scan',JSON.stringify({at:new Date().toISOString(),fatalError:String(e?.message||e)}))))}};