import v14 from './index-v14.js';

// V15 X copy policy: never publish a chopped sentence. V13 remains the scanner/render chain;
// this endpoint/policy is used by the next generated share payload and documents the production rule.
function clean(s=''){return String(s).replace(/\s+/g,' ').trim()}
function sentences(s=''){const x=clean(s);return (x.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]).map(clean).filter(Boolean)}
function ensureEnd(s=''){s=clean(s);return s&&!/[.!?]$/.test(s)?s+'.':s}
function shortTitle(s,max=82){s=clean(s);if(s.length<=max)return s;const cut=s.slice(0,max+1),at=cut.lastIndexOf(' ');return clean(cut.slice(0,at>35?at:max)).replace(/[,:;\-]+$/,'')}
function safeTags(tags=[]){const a=(Array.isArray(tags)?tags:[]).filter(x=>/^#[\p{L}\p{N}_]{2,30}$/u.test(String(x))).slice(0,3);return a.length?a:['#SonDakika','#Gündem']}
export function composeX({title='',description='',hashtags=[]}={}){const hs=safeTags(hashtags).join(' '),head=`🔴 SON DAKİKA | ${shortTitle(title)}`,limit=265;let chosen='';for(const s0 of sentences(description)){const s=ensureEnd(s0);const trial=chosen?`${chosen} ${s}`:s;const full=`${head}\n\n${trial}\n\n${hs}`;if(full.length<=limit)chosen=trial;else break}if(!chosen){const first=sentences(description)[0]||'';if(first){const room=Math.max(35,limit-head.length-hs.length-6);let s=clean(first);if(s.length>room){const c=s.slice(0,room+1),at=c.lastIndexOf(' ');s=clean(c.slice(0,at>25?at:room)).replace(/[,:;\-]+$/,'');const last=s.lastIndexOf(' ');if(last>25)s=s.slice(0,last);s=ensureEnd(s)}chosen=s}}let out=chosen?`${head}\n\n${chosen}\n\n${hs}`:`${head}\n\n${hs}`;if(out.length>280)out=`${head}\n\n${hs}`;return out}
export default{async fetch(req,env,ctx){const u=new URL(req.url);if(u.pathname==='/health'){const r=await v14.fetch(req,env,ctx);let d={};try{d=await r.clone().json()}catch{}return Response.json({...d,version:'sentence-safe-v15',x_sentence_safe:true,x_target_chars:265,x_max_hashtags:3,x_ellipsis_disabled:true})}if(u.pathname==='/x-compose-test'){const title=u.searchParams.get('title')||"5 ilde operasyon: 5 şüpheli gözaltına alındı",description=u.searchParams.get('description')||"Kızılcahamam Cumhuriyet Başsavcılığı koordinesinde yürütülen soruşturma kapsamında 5 ilde eş zamanlı operasyon düzenlendi. Operasyonda 5 şüpheli gözaltına alındı.",hashtags=(u.searchParams.get('hashtags')||'#SonDakika,#Gündem').split(',');const text=composeX({title,description,hashtags});return Response.json({status:'ok',version:'sentence-safe-v15',length:text.length,complete_sentence:!text.includes('…')&&!/\.\.\./.test(text),text})}return v14.fetch(req,env,ctx)},async scheduled(event,env,ctx){return v14.scheduled(event,env,ctx)}};
