import v8 from './index-v8.js';

// V9: live feed quality telemetry. This does not weaken V7/V8 verification.
const FEEDS=[
['AA Politika','https://www.aa.com.tr/tr/teyithatti/rss/news?cat=politika'],['AA Ekonomi','https://www.aa.com.tr/tr/teyithatti/rss/news?cat=ekonomi'],['AA Bilim Teknoloji','https://www.aa.com.tr/tr/teyithatti/rss/news?cat=bilim-teknoloji'],['AA Aktüel','https://www.aa.com.tr/tr/teyithatti/rss/news?cat=aktuel'],['AA Tüm Haberler','https://www.aa.com.tr/tr/teyithatti/rss/news?cat=0'],['Sözcü Son Dakika','https://www.sozcu.com.tr/feeds-son-dakika'],['Sözcü Gündem','https://www.sozcu.com.tr/feeds-rss-category-gundem'],['Sözcü Ekonomi','https://www.sozcu.com.tr/feeds-rss-category-ekonomi'],['TRT Son Dakika','https://www.trthaber.com/sondakika_articles.rss'],['TRT Gündem','https://www.trthaber.com/gundem_articles.rss'],['Habertürk Genel','https://www.haberturk.com/rss'],['Habertürk Gündem','https://www.haberturk.com/rss/kategori/gundem.xml'],['Habertürk Ekonomi','https://www.haberturk.com/rss/ekonomi.xml'],['Haberler.com','https://rss.haberler.com/RssNew.aspx'],['Hürriyet','https://rss.hurriyet.com.tr/']
].map(([name,url])=>({name,url}));
const clean=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
function stats(xml){const blocks=[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,30).map(x=>x[1]);let latest=0,title='';for(const b of blocks){const dm=b.match(/<(?:pubDate|dc:date|date)[^>]*>([\s\S]*?)<\/(?:pubDate|dc:date|date)>/i),tm=b.match(/<title[^>]*>([\s\S]*?)<\/title>/i);const t=dm?Date.parse(clean(dm[1])):NaN;if(Number.isFinite(t)&&t>latest){latest=t;title=clean(tm?.[1]||'')}}const age=latest?Math.max(0,Math.round((Date.now()-latest)/60000)):null;return{items:blocks.length,latest_age_minutes:age,latest_title:title||null,live:blocks.length>0&&age!==null&&age<=180}}
async function probe(){const results=await Promise.all(FEEDS.map(async s=>{const started=Date.now();try{const r=await fetch(s.url,{headers:{'User-Agent':'90Gundem/3.0',Accept:'application/rss+xml, application/xml, text/xml;q=0.9, */*;q=0.5'}});const xml=r.ok?await r.text():'';return{name:s.name,ok:r.ok,status:r.status,latency_ms:Date.now()-started,...stats(xml)}}catch(e){return{name:s.name,ok:false,status:0,latency_ms:Date.now()-started,items:0,latest_age_minutes:null,latest_title:null,live:false,error:String(e)}}}));return{configured:results.length,http_online:results.filter(x=>x.ok).length,producing:results.filter(x=>x.items>0).length,live_3h:results.filter(x=>x.live).length,results}}
export default {async fetch(req,env,ctx){const u=new URL(req.url);if(u.pathname==='/health'){const r=await v8.fetch(req,env,ctx);let d={};try{d=await r.clone().json()}catch{}return Response.json({...d,version:'fast-news-v9',feed_telemetry:true,quality_gate:'http+items+freshness',active:true})}if(u.pathname==='/source-health')return Response.json({status:'ok',version:'fast-news-v9',...(await probe())});return v8.fetch(req,env,ctx)},async scheduled(event,env,ctx){return v8.scheduled(event,env,ctx)}};
