import { enrichNews } from './openrouter.js';
const FEEDS=[['TRT Haber','TRT Haber','https://www.trthaber.com/sondakika_articles.rss'],['TRT Gündem','TRT Haber','https://www.trthaber.com/gundem_articles.rss'],['Habertürk','Habertürk','https://www.haberturk.com/rss'],['Habertürk Gündem','Habertürk','https://www.haberturk.com/rss/kategori/gundem.xml'],['Habertürk Ekonomi','Habertürk','https://www.haberturk.com/rss/ekonomi.xml'],['Haberler.com','Haberler.com','https://rss.haberler.com/RssNew.aspx'],['Sözcü Son Dakika','Sözcü','https://www.sozcu.com.tr/feeds-son-dakika'],['Sözcü Gündem','Sözcü','https://www.sozcu.com.tr/feeds-rss-category-gundem'],['Sözcü Ekonomi','Sözcü','https://www.sozcu.com.tr/feeds-rss-category-ekonomi'],['Hürriyet','Hürriyet','https://rss.hurriyet.com.tr/']].map(([source,publisher,url])=>({source,publisher,url}));
const STOP=new Set('ve veya ile için bir bu şu o da de son dakika haber haberi haberleri yeni göre olarak daha en çok ise var oldu olan ilgili ardından sonra önce bugün türkiye açıklama açıkladı gelişme gelişmeler sıcak flaş'.split(' '));
const xmlDecode=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const text=s=>xmlDecode(s).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const esc=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const compact=(s,n)=>{s=String(s||'').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n-1).trimEnd()+'…':s};
const norm=s=>text(s).toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü ]/gi,' ').replace(/\s+/g,' ').trim();
const toks=s=>new Set(norm(s).split(' ').filter(x=>x.length>2&&!STOP.has(x)));
function imageFromBlock(b){const patterns=[/<media:content\b[^>]*\burl=["']([^"']+)["']/i,/<media:thumbnail\b[^>]*\burl=["']([^"']+)["']/i,/<enclosure\b[^>]*\burl=["']([^"']+)["'][^>]*(?:type=["']image\/[^"']+["'])?/i,/<img\b[^>]*\bsrc=["']([^"']+)["']/i];for(const p of patterns){const m=b.match(p);if(m?.[1]&&/^https?:\/\//i.test(xmlDecode(m[1])))return xmlDecode(m[1])}return ''}
function parse(xml,f){return[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].slice(0,15).map(m=>{const b=m[1],g=t=>text(b.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`,'i'))?.[1]||'');return{title:g('title'),description:g('description'),link:g('link')||g('guid'),pubDate:g('pubDate')||g('dc:date')||g('date'),image:imageFromBlock(b),source:f.source,publisher:f.publisher}})}
async function ogImage(url){if(!url||!/^https?:\/\//i.test(url))return '';try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; 90Gundem/1.0)'} ,redirect:'follow'});if(!r.ok)return '';const h=(await r.text()).slice(0,350000);const m=h.match(/<meta[^>]+(?:property|name)=["'](?:og:image|twitter:image(?::src)?)["'][^>]+content=["']([^"']+)["']/i)||h.match(/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["'](?:og:image|twitter:image(?::src)?)["']/i);if(!m?.[1])return '';return new URL(xmlDecode(m[1]),url).href}catch{return ''}}
async function ensureImage(item){if(item.image)return item;return{...item,image:await ogImage(item.link)}}
function score(a,b){const A=toks(a),B=toks(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;const r=n/Math.min(A.size,B.size);return n>=3&&r>=.38?Math.max(.60,r):n>=2&&r>=.5?Math.max(.56,r):r}
function clusters(items){const out=[];for(const i of items){let best=null,bs=0;for(const c of out){let s=0;for(const x of c.items)s=Math.max(s,score(i.title,x.title));if(s>bs){bs=s;best=c}}if(best&&bs>=.52){best.items.push(i);best.publishers.add(i.publisher);if(new Date(i.pubDate)>new Date(best.primary.pubDate))best.primary=i}else out.push({primary:i,items:[i],publishers:new Set([i.publisher])})}return out.filter(c=>c.publishers.size>=2).sort((a,b)=>new Date(b.primary.pubDate)-new Date(a.primary.pubDate))}
async function fingerprint(c){const count=new Map();for(const i of c.items)for(const t of toks(i.title))count.set(t,(count.get(t)||0)+1);let a=[...count].filter(([,n])=>n>=2).map(([t])=>t).sort();if(a.length<2)a=[...toks(c.primary.title)].sort().slice(0,6);const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(a.slice(0,8).join('|')));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,48)}
async function schema(env){await env.DB.batch([env.DB.prepare('CREATE TABLE IF NOT EXISTS worker_state(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'),env.DB.prepare("CREATE TABLE IF NOT EXISTS news_queue(fingerprint TEXT PRIMARY KEY,title TEXT NOT NULL,source_url TEXT,primary_source TEXT NOT NULL,sources TEXT NOT NULL,source_count INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'ready',first_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare('CREATE TABLE IF NOT EXISTS news_content(fingerprint TEXT PRIMARY KEY,title TEXT NOT NULL,description TEXT,hashtags TEXT,visual_prompt TEXT,ai_model TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)')])}
async function state(env,k,v){if(v!==undefined){await env.DB.prepare('INSERT INTO worker_state(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind(k,String(v)).run();return}return(await env.DB.prepare('SELECT value FROM worker_state WHERE key=?').bind(k).first())?.value??null}
async function fetchFeeds(){return Promise.all(FEEDS.map(async f=>{try{const r=await fetch(f.url,{headers:{'User-Agent':'90Gundem/1.0',Accept:'application/rss+xml, application/xml, text/xml;q=0.9, */*;q=0.5'}});return{...f,ok:r.ok,status:r.status,items:r.ok?parse(await r.text(),f):[]}}catch(e){return{...f,ok:false,status:0,items:[],error:String(e)}}}))}
async function latest(maxAge=60){const f=await fetchFeeds(),all=f.flatMap(x=>x.items),now=Date.now(),fresh=all.filter(i=>{const t=new Date(i.pubDate).getTime(),a=now-t;return i.title&&Number.isFinite(t)&&a>=0&&a<=maxAge*60000}).sort((a,b)=>new Date(b.pubDate)-new Date(a.pubDate));return{f,all,fresh,c:clusters(fresh)}}
function tags(i){if(i.ai_hashtags?.length)return i.ai_hashtags.join(' ');const n=norm(i.title+' '+(i.description||'')),h=['#SonDakika','#Gündem'],rules=[['erdoğan','#Erdoğan'],['galatasaray','#Galatasaray'],['fenerbahçe','#Fenerbahçe'],['beşiktaş','#Beşiktaş'],['trabzonspor','#Trabzonspor'],['emekli','#Emeklilik'],['kpss','#KPSS'],['deprem','#Deprem'],['ekonomi','#Ekonomi'],['teknoloji','#Teknoloji']];for(const[k,v]of rules)if(n.includes(k)&&!h.includes(v))h.push(v);return h.slice(0,7).join(' ')}
function share(i){let s=`🔴 SON DAKİKA | ${compact(i.title,105)}\n\n${compact(i.description,135)}\n\n${tags(i)}`;if(s.length>280)s=`🔴 ${compact(i.title,115)}\n\n${compact(i.description,85)}\n\n${tags(i)}`;return s.slice(0,280)}
function card(i){const bg=i.image?`<img class="photo" src="${esc(i.image)}">`:'';return`<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;width:1080px;height:1080px;overflow:hidden;font-family:Arial,sans-serif;background:#080a0e;color:#fff}.c{width:1080px;height:1080px;position:relative;overflow:hidden;background:radial-gradient(circle at 80% 10%,#5b111b,#090b10 55%)}.photo{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.9) contrast(1.06)}.shade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(3,5,8,.16) 0%,rgba(3,5,8,.35) 35%,rgba(3,5,8,.92) 70%,#05070a 100%)}.brand{position:absolute;left:48px;top:42px;display:flex;align-items:center;gap:18px}.logo{width:105px;height:105px;border:6px solid #ed1c2b;border-radius:55px;background:rgba(0,0,0,.88);display:flex;align-items:center;justify-content:center;font-size:42px;font-weight:1000;font-style:italic}.logo b{color:#ed1c2b}.name{font-size:38px;font-weight:900;text-shadow:0 3px 12px #000}.trust{font-size:17px;letter-spacing:5px;color:#ddd;margin-top:5px}.breaking{position:absolute;left:48px;top:180px;background:#e51d2a;padding:13px 25px;font-size:24px;font-weight:900;letter-spacing:2px;transform:skew(-5deg)}.content{position:absolute;left:48px;right:48px;bottom:82px}.title{font-size:58px;line-height:1.02;font-weight:1000;text-transform:uppercase;text-shadow:0 4px 16px #000;max-height:250px;overflow:hidden}.redline{height:9px;width:190px;background:#ed1c2b;margin:24px 0}.desc{font-size:28px;line-height:1.35;color:#f0f0f0;text-shadow:0 2px 8px #000;max-height:125px;overflow:hidden}.foot{margin-top:28px;padding-top:18px;border-top:1px solid rgba(255,255,255,.35);display:flex;justify-content:space-between;font-size:18px;font-weight:700}.source{color:#ddd}</style></head><body><div class="c">${bg}<div class="shade"></div><div class="brand"><div class="logo">90<b>+</b></div><div><div class="name">90+ GÜNDEM</div><div class="trust">HIZLI • DOĞRU • GÜVENİLİR</div></div></div><div class="breaking">SON DAKİKA</div><div class="content"><div class="title">${esc(i.title)}</div><div class="redline"></div><div class="desc">${esc(i.description)}</div><div class="foot"><span>DOĞRULANMIŞ HABER</span><span class="source">${esc((i.sources||[]).join(' • '))}</span></div></div></div></body></html>`}
async function png(env,i){if(!env.BROWSER)throw new Error('BROWSER binding missing');const r=await env.BROWSER.quickAction('screenshot',{html:card(i),viewport:{width:1080,height:1080},screenshotOptions:{type:'png',fullPage:false}});if(!r.ok)throw new Error(`browser_screenshot_${r.status}:${await r.text()}`);return new Uint8Array(await r.arrayBuffer())}
async function chatId(env){return env.TELEGRAM_CHAT_ID||await state(env,'telegram_chat_id')}
async function sendPhoto(env,i){const id=await chatId(env);if(!id||!env.TELEGRAM_BOT_TOKEN)return false;const bytes=await png(env,i),form=new FormData();form.append('chat_id',String(id));form.append('photo',new Blob([bytes],{type:'image/png'}),`90gundem-${i.fp}.png`);form.append('caption',`📰 90+ GÜNDEM\n\n${compact(i.title,180)}\n\n${compact(i.description,420)}\n\nKaynaklar: ${i.sources.join(' • ')}\nDoğrulama: ${i.sources.length} bağımsız yayıncı\n\n${tags(i)}`);form.append('reply_markup',JSON.stringify({inline_keyboard:[[{text:'𝕏 METNİ X’TE AÇ',url:`https://twitter.com/intent/tweet?text=${encodeURIComponent(share(i))}`}]]}));const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendPhoto`,{method:'POST',body:form}),j=await r.json();if(!j.ok)throw new Error(`telegram_sendPhoto:${JSON.stringify(j).slice(0,250)}`);return true}
async function makeItem(env,c){let base=await ensureImage(c.primary),i=base;try{if(env.OPENROUTER_API_KEY){const ai=await enrichNews(env,c);i={...base,...ai,image:base.image,link:base.link,pubDate:base.pubDate,source:base.source,publisher:base.publisher}}}catch{}return i}
async function scan(env,maxAge=null,mode='scheduled'){await schema(env);const age=maxAge??Number(env.X_MAX_AGE_MINUTES||3),d=await latest(age);let notified=0,skipped=0,withImage=0,lastError=null;for(const c of d.c.slice(0,5)){const f=await fingerprint(c),sources=[...c.publishers],old=await env.DB.prepare('SELECT status FROM news_queue WHERE fingerprint=?').bind(f).first();if(old){skipped++;continue}let i=await makeItem(env,c);i={...i,fp:f,sources};if(i.image)withImage++;await env.DB.prepare("INSERT INTO news_queue(fingerprint,title,source_url,primary_source,sources,source_count,status) VALUES(?,?,?,?,?,?,'ready')").bind(f,i.title,i.link||c.primary.link,c.primary.source,JSON.stringify(sources),sources.length).run();await env.DB.prepare('INSERT OR REPLACE INTO news_content(fingerprint,title,description,hashtags,visual_prompt,ai_model,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(f,i.title,i.description||'',JSON.stringify(i.ai_hashtags||[]),i.visual_prompt||'',i.ai_model||'').run();try{if(await sendPhoto(env,i)){await env.DB.prepare("UPDATE news_queue SET status='share_ready' WHERE fingerprint=?").bind(f).run();notified++}}catch(e){lastError=String(e?.message||e)}}const s={at:new Date().toISOString(),mode,version:'source-photo-v5',fetched:d.all.length,fresh:d.fresh.length,verified:d.c.length,new_items:d.c.length-skipped,dedupe_skipped:skipped,source_photos:withImage,telegram_notified:notified,lastError};await state(env,'last_scan',JSON.stringify(s));return s}
async function telegramTest(env){const d=await latest(60),c=d.c[0];if(!c)return{status:'ok',sent:false,message:'Doğrulanmış haber yok.'};let i=await makeItem(env,c);i={...i,fp:await fingerprint(c),sources:[...c.publishers]};return{status:'ok',sent:await sendPhoto(env,i),source_image:Boolean(i.image),image_url:i.image||null,title:i.title}}
export default{async fetch(req,env){await schema(env);const u=new URL(req.url);if(u.pathname==='/telegram-test'){try{return Response.json(await telegramTest(env))}catch(e){return Response.json({status:'error',error:String(e?.message||e)},{status:500})}}if(u.pathname==='/run-once'){try{return Response.json({status:'ok',...await scan(env,60,'manual-source-photo-test')})}catch(e){return Response.json({status:'error',error:String(e?.message||e)},{status:500})}}if(u.pathname==='/health')return Response.json({status:'ok',service:'90gundem-cloudflare',version:'source-photo-v5',feeds:FEEDS.length,browser_binding:Boolean(env.BROWSER),openrouter_configured:Boolean(env.OPENROUTER_API_KEY),telegram_ready:Boolean(env.TELEGRAM_BOT_TOKEN&&await chatId(env)),source_photo_cards:true,x_api_publishing:false});if(u.pathname==='/status'){const s=await state(env,'last_scan');return Response.json({status:'ok',last_scan:s?JSON.parse(s):null})}return new Response('90+ GUNDEM source-photo newsroom')},async scheduled(c,env,ctx){ctx.waitUntil(scan(env,null,'scheduled').catch(e=>state(env,'last_scan',JSON.stringify({at:new Date().toISOString(),fatalError:String(e?.message||e)}))))}};